language: python
cache: pip
python:
  - "3.5"
before_install:
  - mv travis_secrets.yaml secrets.yaml
  - mkdir /config
  - touch "/config/ssl_key.pem"
  - touch "/config/ssl_cert.pem"
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
