- id: doorunlocked
  alias: "Door Unlocked"
  trigger:
    - platform: state
      entity_id: lock.back_door_locked
      to: 'unlocked'
      from: 'locked'
    - platform: state
      entity_id: lock.garage_door_locked
      to: 'unlocked'
      from: 'locked'
    - platform: state
      entity_id: lock.front_door_locked
      to: 'unlocked'
      from: 'locked'
  action:
    service: notify.primary_contact
    data_template:
      message: "{{ trigger.to_state.attributes.friendly_name }} has been UNLOCKED"

- id: dooropened
  alias: "Door Opened"
  trigger:
    - platform: state
      entity_id: binary_sensor.back_door
      to: 'on'
      from: 'off'
    - platform: state
      entity_id: binary_sensor.front_door
      to: 'on'
      from: 'off'
    - platform: state
      entity_id: binary_sensor.garage_door
      to: 'on'
      from: 'off'
  action:
    service: notify.primary_contact
    data_template:
      message: "{{ trigger.to_state.attributes.friendly_name }} has been OPENED"

- id: doorclosed
  alias: "Door Closed"
  trigger:
    - platform: state
      entity_id: binary_sensor.back_door
      to: 'off'
      from: 'on'
    - platform: state
      entity_id: binary_sensor.front_door
      to: 'off'
      from: 'on'
    - platform: state
      entity_id: binary_sensor.garage_door
      to: 'off'
      from: 'on'
  action:
    service: notify.primary_contact
    data_template:
      message: "{{ trigger.to_state.attributes.friendly_name }} has been CLOSED"