- id: doorunlocked
  alias: "Door Unlocked"
  trigger:
    - platform: state
      entity_id: lock.back_door_locked
      to: 'unlocked'
      from: 'locked'
    - platform: state
      entity_id: lock.garage_door_locked
      to: 'unlocked'
      from: 'locked'
    - platform: state
      entity_id: lock.front_door_locked
      to: 'unlocked'
      from: 'locked'
  action:
    service: notify.primary_contact
    data_template:
      message: "{{ trigger.to_state.attributes.friendly_name }} has been UNLOCKED"