- alias: 'Sunrise'
  trigger:
    platform: sun
    event: sunrise
    offset: '+00:00:00'
  action:
    - service: light.turn_off
      data:
        entity_id: 
          - light.kitchen_sink_ove_level
    - service: switch.turn_off
      data:
        entity_id:
          - switch.backyard_switch
          - switch.frontyard_switch
    - service: climate.set_temperature
      data:
        entity_id: climate.hallway
        temperature: '72'
    - service: notify.primary_contact
      data:
        message: "Outside lights OFF, Temperature set to DAY level"

- alias: 'Sunset'
  trigger:
    platform: sun
    event: sunset
    offset: '+00:00:00'
  action:
    - service: light.turn_on
      data:
        entity_id: 
          - light.study_cans_level
        brightness: 50
    - service: switch.turn_off
      data:
        entity_id: 
          - switch.study_overhead_switch
    - service: light.turn_on
      data:
        entity_id: 
          - light.kitchen_sink_ove_level
        brightness: 40
    - service: switch.turn_on
      data:
        entity_id:
          - switch.backyard_switch
          - switch.frontyard_switch
    - service: climate.set_temperature
      data:
        entity_id: climate.hallway
        temperature: '68'
    - service: notify.default_notifier
      data:
        message: "Outside lights ON, Doors LOCKED, Temperature set to NIGHT level"