homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: 252
  unit_system: imperial
  time_zone: America/Chicago
  whitelist_external_dirs: !secret white_list_dirs

  #-------------------------------------------
  # Include customizations
  #-------------------------------------------
  customize: !include customize.yaml

  #-------------------------------------------
  # Include GLOB customizations
  #-------------------------------------------
  customize_glob: !include customize_glob.yaml

#-------------------------------------------
# Shell Commands
#-------------------------------------------
shell_command: !include shell_commands.yaml

#-------------------------------------------
# Enable InfluxDB
#-------------------------------------------
influxdb:
  host: !secret internal_host
  
#-------------------------------------------
# Enable InfluxDB
#-------------------------------------------
input_boolean: !include_dir_merge_named input_booleans

#-------------------------------------------
# Recorder Settings
#-------------------------------------------
recorder: !include recorder.yaml

#-------------------------------------------
# Logger Settings
#-------------------------------------------
logger: !include logger.yaml

#-------------------------------------------
# Frontend Settings
#-------------------------------------------
frontend:
  javascript_version: latest

#-------------------------------------------
# iOS App Settings
#-------------------------------------------
ios: !include ios.yaml

#-------------------------------------------
# Enable configuration UI
#-------------------------------------------
config:

#-------------------------------------------
# HTTP Server Config
#-------------------------------------------
http:
  api_password: !secret http_password
  base_url: !secret server_fqdn
  ip_ban_enabled: true
  login_attempts_threshold: 3
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssl_key
  ssl_profile: intermediate
  trusted_networks:
    - 127.0.0.1
    - 192.168.128.0/24

#-------------------------------------------
# Enable Nest
#-------------------------------------------
nest: !include nest.yaml

#-------------------------------------------
# Enable cameras
#-------------------------------------------
camera: !include cameras.yaml

#-------------------------------------------
# Enable covers
#-------------------------------------------
cover: !include cover.yaml

#-------------------------------------------
# MQTT Settings
#-------------------------------------------
mqtt:
  broker: !secret mqtt_host
  discovery: true

#-------------------------------------------
# History support
#-------------------------------------------
history:
  exclude:
    domains:
      - automation

#-------------------------------------------
# Logbook Settings
#-------------------------------------------
logbook: !include logbook.yaml

#-------------------------------------------
# Track the sun
#-------------------------------------------
sun:

#-------------------------------------------
# Home Assistant Cloud
#-------------------------------------------
cloud:

#-------------------------------------------
# Include sensors
#-------------------------------------------
sensor: !include_dir_merge_list sensors

#-------------------------------------------
# Include sensors
#-------------------------------------------
binary_sensor: !include_dir_merge_list binary_sensors

#-------------------------------------------
# Include notifications
#-------------------------------------------
notify: !include notify.yaml

#-------------------------------------------
# Include zones
#-------------------------------------------
zone: !include_dir_list zones

#-------------------------------------------
# Include groups
#-------------------------------------------
group: !include_dir_merge_named groups

#-------------------------------------------
# Include automations
#-------------------------------------------
automation: !include_dir_merge_list automations

#-------------------------------------------
# Zwave Settings
#-------------------------------------------
# note: zwave component totally failed.
# zwave: !include zwave.yaml

#-------------------------------------------
# Scripts
#-------------------------------------------
script: !include_dir_merge_named scripts

#-------------------------------------------
# Device Tracking
#-------------------------------------------
device_tracker: !include device_tracker.yaml

#-------------------------------------------
# Twilio
#-------------------------------------------
twilio:
  account_sid: !secret twilio_sid
  auth_token: !secret twilio_key

#-------------------------------------------
# WirelessTag
#-------------------------------------------
wirelesstag:
  username: !secret sense_username
  password: !secret sense_password

#-------------------------------------------
# Homekit
#-------------------------------------------
homekit: !include homekit.yaml
