homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: 252
  unit_system: imperial
  time_zone: America/Chicago

  #-------------------------------------------
  # Include customizations
  #-------------------------------------------
  customize: !include customize.yaml

#-------------------------------------------
# Recorder Settings
#-------------------------------------------
recorder: !include recorder.yaml

#-------------------------------------------
# Logger Settings
#-------------------------------------------
logger: !include logger.yaml

#-------------------------------------------
# Ring Doorbell Settings
#-------------------------------------------
ring:
  username: !secret ring_username
  password: !secret ring_password

#-------------------------------------------
# Frontend Settings
#-------------------------------------------
frontend:
  javascript_version: latest
  themes:
    red:
      primary-color: red
    orange:
      primary-color: orange
    yellow:
      primary-color: "#cccc00"
    green:
      primary-color: "#009900"

#-------------------------------------------
# iOS App Settings
#-------------------------------------------
ios: !include ios.yaml

#-------------------------------------------
# Twilio Settings
#-------------------------------------------
twilio:
  account_sid: !secret twilio_sid
  auth_token: !secret twilio_token

#-------------------------------------------
# Enable configuration UI
#-------------------------------------------
config:

#-------------------------------------------
# HTTP Server Config
#-------------------------------------------
http:
  api_password: !secret http_password
  base_url: !secret server_fqdn
  ip_ban_enabled: true
  login_attempts_threshold: 3
  ssl_certificate: !secret ssl_cert_path
  ssl_key: !secret ssl_key_path

#-------------------------------------------
# Checks for available updates
#-------------------------------------------
updater:
  include_used_components: true

#-------------------------------------------
# Enable cameras
#-------------------------------------------
camera:
  - platform: amcrest
  - platform: ring

#-------------------------------------------
# Enable covers
#-------------------------------------------
cover: !include covers.yaml

#-------------------------------------------
# Enable light component
#-------------------------------------------
light:
  - platform: lifx

#-------------------------------------------
# Media Players
#-------------------------------------------
#media_player:
#  - platform: directv
#    host: 192.168.128.207
#    port: 8080
#    name: Main DirecTV Box
#    device: 0
#  - platform: directv
#    host: 192.168.128.207
#    port: 8080
#    name: Master Bedroom DirecTV
#    device: 14B7F87C30BF
#  - platform: roku
#    host: 192.168.128.200

#-------------------------------------------
# Nest Settings
#-------------------------------------------
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

#-------------------------------------------
# APCUPSd Settings
#-------------------------------------------
apcupsd:
  host: 127.0.0.1

#-------------------------------------------
# MQTT Settings
#-------------------------------------------
mqtt:
  broker: 127.0.0.1

#-------------------------------------------
# History support
#-------------------------------------------
history:
  
#-------------------------------------------
# Logbook Settings
#-------------------------------------------
logbook: !include logbook.yaml

#-------------------------------------------
# Track the sun
#-------------------------------------------
sun:

#-------------------------------------------
# Text to speech settings
#-------------------------------------------
tts:
  platform: google

#-------------------------------------------
# Include sensors
#-------------------------------------------
sensor: !include_dir_merge_list sensors

#-------------------------------------------
# Include sensors
#-------------------------------------------
binary_sensor: !include_dir_merge_list binary_sensors

#-------------------------------------------
# Include notifications
#-------------------------------------------
notify: !include notify.yaml

#-------------------------------------------
# Include zones
#-------------------------------------------
zone: !include_dir_list zones

#-------------------------------------------
# Include groups
#-------------------------------------------
group: !include_dir_merge_named groups

#-------------------------------------------
# Include automations
#-------------------------------------------
automation: !include_dir_merge_list automations

#-------------------------------------------
# Zwave Settings
#-------------------------------------------
zwave: !include zwave.yaml

#-------------------------------------------
# Scripts
#-------------------------------------------
script: !include_dir_merge_named scripts

#-------------------------------------------
# Include alerts
#-------------------------------------------
alert: !include alerts.yaml

#-------------------------------------------
# Include aleamcrestrts
#-------------------------------------------
amcrest: !include amcrest.yaml

#-------------------------------------------
# Eight Sleep Setup
#-------------------------------------------
eight_sleep:
  username: !secret eight_sleep_user
  password: !secret eight_sleep_pass
  partner: true

#-------------------------------------------
# Device Tracking
#-------------------------------------------
device_tracker: !include device_tracker.yaml

#-------------------------------------------
# Weblinks
#-------------------------------------------
weblink:
  entities:
    - name: Meraki Management
      url: https://account.meraki.com/secure/login/dashboard_login
      icon: mdi:router-wireless
    - name: Montastic
      url: https://www.montastic.com
      icon: mdi:security-network
    - name: Nagios
      url: http://192.168.128.163/nagios/
      icon: mdi:ethernet
    - name: Rancher
      url: http://192.168.128.253:8080
      icon: mdi:cow