homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: 252
  unit_system: imperial
  time_zone: America/Chicago

  #-------------------------------------------
  # Include customizations
  #-------------------------------------------
  customize: !include_dir_merge_named customizations

  #-------------------------------------------
  # Include packages
  #-------------------------------------------
  packages: !include_dir_named packages

#-------------------------------------------
# Recorder Settings
#-------------------------------------------
recorder:
  db_url: !secret mysql_log_conn
  purge_days: 30
  exclude:
    domains:
      - zwave
    entities:
      - sensor.pws_alerts

#-------------------------------------------
# Logger Settings
#-------------------------------------------
logger: !include logger.yaml

#-------------------------------------------
# Frontend Settings
#-------------------------------------------
frontend:
  themes:
    red:
      primary-color: red
    orange:
      primary-color: orange
    yellow:
      primary-color: "#cccc00"
    green:
      primary-color: "#009900"

#-------------------------------------------
# iOS App Settings
#-------------------------------------------
ios:

#-------------------------------------------
# Enable configuration UI
#-------------------------------------------
config:

#-------------------------------------------
# HTTP Server Config
#-------------------------------------------
http:
  api_password: !secret http_password
  base_url: !secret server_fqdn
  ip_ban_enabled: true
  login_attempts_threshold: 3

#-------------------------------------------
# Checks for available updates
#-------------------------------------------
updater:
  include_used_components: true

#-------------------------------------------
# Enable Auto-discover (what we can)
#-------------------------------------------
# discovery:

#-------------------------------------------
# MQTT Settings
#-------------------------------------------
mqtt:
  broker: !secret cloudmqtt_url
  port: !secret cloudmqtt_port
  username: !secret cloudmqtt_user
  password: !secret cloudmqtt_pass

#-------------------------------------------
# History support
#-------------------------------------------
history:
  exclude:
    domains:
      - zwave
      - weblink
      - script
      - sun

#-------------------------------------------
# Logbook Settings
#-------------------------------------------
logbook: !include logbook.yaml

#-------------------------------------------
# Track the sun
#-------------------------------------------
sun:

#-------------------------------------------
# Text to speech settings
#-------------------------------------------
tts:
  platform: google

#-------------------------------------------
# Include sensors
#-------------------------------------------
input_select: !include input_select.yaml

#-------------------------------------------
# Include sensors
#-------------------------------------------
sensor: !include_dir_merge_list sensors

#-------------------------------------------
# Include sensors
#-------------------------------------------
binary_sensor: !include_dir_merge_list bsensors

#-------------------------------------------
# Include notifications
#-------------------------------------------
notify: !include notify.yaml

#-------------------------------------------
# Include zones
#-------------------------------------------
zone: !include_dir_list zones

#-------------------------------------------
# Include groups
#-------------------------------------------
group: !include_dir_merge_named groups

#-------------------------------------------
# Include automations
#-------------------------------------------
automation: !include automation.yaml

#-------------------------------------------
# Zwave Settings
#-------------------------------------------
zwave: !include zwave.yaml

#-------------------------------------------
# Scripts
#-------------------------------------------
script: !include_dir_merge_named scripts

#-------------------------------------------
# Include alerts
#-------------------------------------------
alert: !include alerts.yaml
