homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: 252
  unit_system: imperial
  time_zone: America/Chicago
  whitelist_external_dirs: !secret whitelist_dirs
  customize: !include customize.yaml

#-------------------------------------------
# Shell Commands
#-------------------------------------------
shell_command: !include shell_commands.yaml

#-------------------------------------------
# Enable InfluxDB
#-------------------------------------------
influxdb:
  host: !secret ip_influxdb
  username: !secret influx_user
  password: !secret influx_pass
  database: !secret influx_db
  ssl: true
  verify_ssl: false

#-------------------------------------------
# Enable Prometheus
#-------------------------------------------
prometheus:

#-------------------------------------------
# Web Config
#-------------------------------------------
config:

#-------------------------------------------
# Input Booleans
#-------------------------------------------
input_boolean: !include_dir_merge_named input_booleans

#-------------------------------------------
# Recorder Settings
#-------------------------------------------
recorder: !include recorder.yaml

#-------------------------------------------
# Logger Settings
#-------------------------------------------
logger: !include logger.yaml

#-------------------------------------------
# Frontend Settings
#-------------------------------------------
frontend:
  javascript_version: latest

#-------------------------------------------
# HTTP Server Config
#-------------------------------------------
http:
  base_url: !secret server_url
  ip_ban_enabled: true
  login_attempts_threshold: 3
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssl_key

#-------------------------------------------
# Enable cameras
#-------------------------------------------
camera: !include cameras.yaml

#-------------------------------------------
# Enable covers
#-------------------------------------------
cover: !include cover.yaml

#-------------------------------------------
# MQTT Settings
#-------------------------------------------
mqtt:
  broker: !secret ip_mosquitto
  discovery: true

#-------------------------------------------
# History support
#-------------------------------------------
history:

#-------------------------------------------
# Logbook Settings
#-------------------------------------------
logbook: !include logbook.yaml

#-------------------------------------------
# Track the sun
#-------------------------------------------
sun:

#-------------------------------------------
# Include sensors
#-------------------------------------------
sensor: !include_dir_merge_list sensors

#-------------------------------------------
# Include sensors
#-------------------------------------------
binary_sensor: !include_dir_merge_list binary_sensors

#-------------------------------------------
# Include notifications
#-------------------------------------------
notify: !include notify.yaml

#-------------------------------------------
# Include groups
#-------------------------------------------
group: !include_dir_merge_named groups

#-------------------------------------------
# Include automations
#-------------------------------------------
automation: !include_dir_merge_list automations

#-------------------------------------------
# Device Tracking
#-------------------------------------------
device_tracker: !include device_tracker.yaml

#-------------------------------------------
# WirelessTag
#-------------------------------------------
wirelesstag:
  username: !secret wirelesstag_user
  password: !secret wirelesstag_pass

#-------------------------------------------
# Homekit
#-------------------------------------------
homekit: !include homekit.yaml

#-------------------------------------------
# Amcrest
#-------------------------------------------
amcrest: !include amcrest.yaml

#-------------------------------------------
# Zwave
#-------------------------------------------
zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_key