homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: 252
  unit_system: imperial
  time_zone: America/Chicago
  whitelist_external_dirs: /config/www

  #-------------------------------------------
  # Include customizations
  #-------------------------------------------
  customize: !include customize.yaml

  #-------------------------------------------
  # Include GLOB customizations
  #-------------------------------------------
  customize_glob: !include customize_glob.yaml

#-------------------------------------------
# Recorder Settings
#-------------------------------------------
recorder: !include recorder.yaml

#-------------------------------------------
# Logger Settings
#-------------------------------------------
logger: !include logger.yaml

#-------------------------------------------
# Image Processing
#-------------------------------------------
image_processing: !include image_processing.yaml

#-------------------------------------------
# Ring Doorbell Settings
#-------------------------------------------
ring:
  username: !secret ring_username
  password: !secret ring_password

#-------------------------------------------
# Frontend Settings
#-------------------------------------------
frontend:
  javascript_version: latest

#-------------------------------------------
# iOS App Settings
#-------------------------------------------
ios: !include ios.yaml

#-------------------------------------------
# Enable configuration UI
#-------------------------------------------
config:

#-------------------------------------------
# HTTP Server Config
#-------------------------------------------
http:
  api_password: !secret http_password
  base_url: !secret server_fqdn
  ip_ban_enabled: true
  login_attempts_threshold: 3
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key

#-------------------------------------------
# Checks for available updates
#-------------------------------------------
updater:
  include_used_components: true

#-------------------------------------------
# Enable cameras
#-------------------------------------------
camera:
  - platform: amcrest
  - platform: ring

#-------------------------------------------
# Enable covers
#-------------------------------------------
cover: !include covers.yaml

#-------------------------------------------
# Ecobee Settings
#-------------------------------------------
ecobee:
  api_key: !secret ecobee_key 

#-------------------------------------------
# MQTT Settings
#-------------------------------------------
mqtt:
  broker: !secret mqttconn
  
#-------------------------------------------
# InfluxDB
#-------------------------------------------
influxdb:
  host: !secret influxconn

#-------------------------------------------
# History support
#-------------------------------------------
history:

#-------------------------------------------
# Logbook Settings
#-------------------------------------------
logbook: !include logbook.yaml

#-------------------------------------------
# Track the sun
#-------------------------------------------
sun:

#-------------------------------------------
# Home Assistant Cloud
#-------------------------------------------
cloud:

#-------------------------------------------
# Text to speech settings
#-------------------------------------------
tts:
  platform: google

#-------------------------------------------
# Include sensors
#-------------------------------------------
sensor: !include_dir_merge_list sensors

#-------------------------------------------
# Include sensors
#-------------------------------------------
binary_sensor: !include_dir_merge_list binary_sensors

#-------------------------------------------
# Include notifications
#-------------------------------------------
notify: !include notify.yaml

#-------------------------------------------
# Twilio Info
#-------------------------------------------
twilio:
  account_sid: !secret twilio_sid
  auth_token: !secret twilio_token

#-------------------------------------------
# Include zones
#-------------------------------------------
zone: !include_dir_list zones

#-------------------------------------------
# Include groups
#-------------------------------------------
group: !include_dir_merge_named groups

#-------------------------------------------
# Include automations
#-------------------------------------------
automation: !include_dir_merge_list automations

#-------------------------------------------
# Zwave Settings
#-------------------------------------------
zwave: !include zwave.yaml

#-------------------------------------------
# Scripts
#-------------------------------------------
script: !include_dir_merge_named scripts

#-------------------------------------------
# Include alerts
#-------------------------------------------
alert: !include alerts.yaml

#-------------------------------------------
# Include aleamcrestrts
#-------------------------------------------
amcrest: !include amcrest.yaml

#-------------------------------------------
# Eight Sleep Setup
#-------------------------------------------
eight_sleep:
  username: !secret eight_sleep_user
  password: !secret eight_sleep_pass
  partner: true

#-------------------------------------------
# Device Tracking
#-------------------------------------------
device_tracker: !include device_tracker.yaml
