homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: 252
  unit_system: imperial
  time_zone: America/Chicago
  whitelist_external_dirs: !secret white_list_dirs

#-------------------------------------------
# Shell Commands
#-------------------------------------------
shell_command: !include shell_commands.yaml

#-------------------------------------------
# Enable InfluxDB
#-------------------------------------------
influxdb:
  host: !secret internal_host
  ssl: true
  
#-------------------------------------------
# Input Booleans
#-------------------------------------------
input_boolean: !include_dir_merge_named input_booleans

#-------------------------------------------
# Recorder Settings
#-------------------------------------------
recorder: !include recorder.yaml

#-------------------------------------------
# Logger Settings
#-------------------------------------------
logger: !include logger.yaml

#-------------------------------------------
# Frontend Settings
#-------------------------------------------
frontend:
  javascript_version: latest

#-------------------------------------------
# Enable configuration UI
#-------------------------------------------
config:

#-------------------------------------------
# HTTP Server Config
#-------------------------------------------
http:
  base_url: !secret server_fqdn
#  server_port: 8123
  ip_ban_enabled: true
  login_attempts_threshold: 3
#  ssl_certificate: !secret ssl_cert
#  ssl_key: !secret ssl_key
  trusted_networks:
    - 127.0.0.1
    - 192.168.1.0/24

#-------------------------------------------
# Enable cameras
#-------------------------------------------
camera: !include cameras.yaml

#-------------------------------------------
# Enable covers
#-------------------------------------------
cover: !include cover.yaml

#-------------------------------------------
# MQTT Settings
#-------------------------------------------
mqtt:
  broker: !secret mqtt_host
  discovery: true

#-------------------------------------------
# History support
#-------------------------------------------
history:
  exclude:
    domains:
      - automation

#-------------------------------------------
# Logbook Settings
#-------------------------------------------
logbook: !include logbook.yaml

#-------------------------------------------
# Track the sun
#-------------------------------------------
sun:

#-------------------------------------------
# Include sensors
#-------------------------------------------
sensor: !include_dir_merge_list sensors

#-------------------------------------------
# Include sensors
#-------------------------------------------
binary_sensor: !include_dir_merge_list binary_sensors

#-------------------------------------------
# Include notifications
#-------------------------------------------
notify: !include notify.yaml

#-------------------------------------------
# Include groups
#-------------------------------------------
group: !include_dir_merge_named groups

#-------------------------------------------
# Include automations
#-------------------------------------------
automation: !include_dir_merge_list automations

#-------------------------------------------
# Device Tracking
#-------------------------------------------
device_tracker: !include device_tracker.yaml

#-------------------------------------------
# Twilio
#-------------------------------------------
# Disabled until this is fixed:
# https://github.com/home-assistant/home-assistant/issues/18246
#twilio:
#  account_sid: !secret twilio_sid
#  auth_token: !secret twilio_key

#-------------------------------------------
# WirelessTag
#-------------------------------------------
wirelesstag:
  username: !secret sense_username
  password: !secret sense_password

#-------------------------------------------
# Homekit
#-------------------------------------------
homekit: !include homekit.yaml

#-------------------------------------------
# Amcrest
#-------------------------------------------
amcrest: !include amcrest.yaml