homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: 252
  unit_system: imperial
  time_zone: America/Chicago
  whitelist_external_dirs: !secret white_list_dirs

  #-------------------------------------------
  # Include customizations
  #-------------------------------------------
  customize: !include customize.yaml

  #-------------------------------------------
  # Include GLOB customizations
  #-------------------------------------------
  customize_glob: !include customize_glob.yaml

#-------------------------------------------
# Shell Commands
#-------------------------------------------
shell_command: !include shell_commands.yaml

#-------------------------------------------
# Recorder Settings
#-------------------------------------------
recorder: !include recorder.yaml

#-------------------------------------------
# Logger Settings
#-------------------------------------------
logger: !include logger.yaml

#-------------------------------------------
# Frontend Settings
#-------------------------------------------
frontend:
  javascript_version: latest

#-------------------------------------------
# iOS App Settings
#-------------------------------------------
ios: !include ios.yaml

#-------------------------------------------
# Enable configuration UI
#-------------------------------------------
config:

#-------------------------------------------
# HTTP Server Config
#-------------------------------------------
http:
  api_password: !secret http_password
  base_url: !secret server_fqdn
  ip_ban_enabled: true
  login_attempts_threshold: 3
  ssl_certificate: ssl.crt
  ssl_key: ssl.key
  trusted_networks:
    - 127.0.0.1
    - 192.168.7.0/24
    - 192.168.128.0/24

#-------------------------------------------
# Checks for available updates
#-------------------------------------------
updater:
  include_used_components: true

#-------------------------------------------
# Enable cameras
#-------------------------------------------
camera:
  - platform: amcrest

#-------------------------------------------
# Enable prometheus metrics
#-------------------------------------------
prometheus:

#-------------------------------------------
# Enable covers
#-------------------------------------------
cover: !include covers.yaml

#-------------------------------------------
# Ecobee Settings
#-------------------------------------------
ecobee:
  api_key: !secret ecobee_key 

#-------------------------------------------
# MQTT Settings
#-------------------------------------------
mqtt:
  broker: ubuntu.fuzzyblender.com

#-------------------------------------------
# History support
#-------------------------------------------
history:

#-------------------------------------------
# Logbook Settings
#-------------------------------------------
logbook: !include logbook.yaml

#-------------------------------------------
# Track the sun
#-------------------------------------------
sun:

#-------------------------------------------
# Home Assistant Cloud
#-------------------------------------------
cloud:

#-------------------------------------------
# Text to speech settings
#-------------------------------------------
tts:
  platform: google

#-------------------------------------------
# Include sensors
#-------------------------------------------
sensor: !include_dir_merge_list sensors

#-------------------------------------------
# Include sensors
#-------------------------------------------
binary_sensor: !include_dir_merge_list binary_sensors

#-------------------------------------------
# Include notifications
#-------------------------------------------
notify: !include notify.yaml

#-------------------------------------------
# Twilio Info
#-------------------------------------------
twilio:
  account_sid: !secret twilio_sid
  auth_token: !secret twilio_token

#-------------------------------------------
# Include zones
#-------------------------------------------
zone: !include_dir_list zones

#-------------------------------------------
# Include groups
#-------------------------------------------
group: !include_dir_merge_named groups

#-------------------------------------------
# Include automations
#-------------------------------------------
automation: !include_dir_merge_list automations

#-------------------------------------------
# Zwave Settings
#-------------------------------------------
zwave: !include zwave.yaml

#-------------------------------------------
# Scripts
#-------------------------------------------
script: !include_dir_merge_named scripts

#-------------------------------------------
# Include aleamcrestrts
#-------------------------------------------
amcrest: !include amcrest.yaml

#-------------------------------------------
# Device Tracking
#-------------------------------------------
device_tracker: !include device_tracker.yaml
