
- platform: mqtt
  name: "Chris Garage Door"
  command_topic: "garadget/chris/command"
  state_topic: "garadget/chris/status"
  payload_open: "open"
  payload_close: "close"
  state_open: "open"
  state_closed: "closed"
  value_template: '{{ value_json.status }}'

- platform: mqtt
  name: "Megan Garage Door"
  command_topic: "garadget/megan/command"
  state_topic: "garadget/megan/status"
  payload_open: "open"
  payload_close: "close"
  state_open: "open"
  state_closed: "closed"
  value_template: '{{ value_json.status }}'