#-------------------------------------------
#  Garage Door Cover Megan
#-------------------------------------------
- platform: opengarage
  covers:
    garage:
      host: 192.168.128.227
      device_key: !secret opengarage_key
      name:  Megan Overhead Garage Door

#-------------------------------------------
#  Garage Door Cover Chris
#-------------------------------------------
- platform: opengarage
  covers:
    garage:
      host: 192.168.128.248
      device_key: !secret opengarage_key
      name:  Chris Overhead Garage Door