#-------------------------------------------
# unifi controller
#-------------------------------------------
- platform: unifi
  host: !secret cloud_key_site
  username: !secret cloud_key_user
  password: !secret cloud_key_pass
  verify_ssl: false
