#-------------------------------------------
# Car Tracking
#-------------------------------------------
- platform: automatic
  client_id: !secret automatic_client_id
  secret: !secret automatic_secret

#-------------------------------------------
# Meraki Location Analytics
#-------------------------------------------
- platform: meraki
  secret: meraki_secret
  validator: meraki_validator