#-------------------------------------------
# Car Tracking
#-------------------------------------------
- platform: automatic
  client_id: !secret automatic_client_id
  secret: !secret automatic_secret
#    current_location: true

#-------------------------------------------
# Nmap Tracking
#-------------------------------------------
- platform: nmap_tracker
  hosts: 192.168.128.0/24
  interval_seconds: 60
  consider_home: 180
  track_new_devices: false