#-------------------------------------------
# Car Tracking
#-------------------------------------------
- platform: automatic
  client_id: !secret automatic_client_id
  secret: !secret automatic_secret

#-------------------------------------------
# Meraki Tracking
#-------------------------------------------
- platform: meraki
  secret: !secret meraki_secret
  validator: !secret meraki_validator