version: '2'

services:
  home-assistant:
    image: homeassistant/home-assistant:latest
    network_mode: host
    depends_on:
      - postgres
      - influxdb
      - mosquitto
    volumes:
      - /srv/home-assistant:/config
      - /etc/letsencrypt/:/etc/letsencrypt
    restart: always
  
  postgres:
    image: postgres:alpine
    network_mode: host
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /etc/letsencrypt/:/etc/letsencrypt
    environment:
      POSTGRES_USER: homeassistant
      POSTGRES_PASSWORD: homeassistant
  
  mosquitto:
    image: eclipse-mosquitto:latest
    network_mode: host
    restart: always
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt
      - /srv/mosquitto/data:/mosquitto/data
      - /srv/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /srv/mosquitto/log:/mosquitto/log

  honeywell2mqtt:
    image: chriskacerguis/honeywell2mqtt:2.0.0
    restart: always
    depends_on:
      - mosquitto

  influxdb:
    image: influxdb:alpine
    network_mode: host
    restart: always
    volumes:
      - influxdb:/var/lib/influxdb
      - /etc/letsencrypt/:/etc/letsencrypt
    environment:
      INFLUXDB_DB: home_assistant

#  portainer:
#    image: portainer/portainer
#    network_mode: host
#    restart: always
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - portainer_data:/data
#      - /etc/letsencrypt/:/etc/letsencrypt
#    network_mode: "bridge"
#    command: --ssl --sslcert /etc/letsencrypt/live/fuzzyblender.com/fullchain.pem --sslkey /etc/letsencrypt/live/fuzzyblender.com/privkey.pem

volumes:
#  portainer_data:
  postgres_data:
  influxdb_data: