version: '3.7'

services:

  # Traefik Reverse Proxy
  traefik:
    image: traefik:alpine
    container_name: traefik
    domainname: ${DOMAINNAME}
    restart: always
    networks:
      - default
      - traefik_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${USERDIR}/traefik:/etc/traefik
      - ${USERDIR}/shared:/shared

  # Database of champions
  postgres:
    container_name: postgres
    image: postgres:alpine
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ${USERDIR}/postgres:/var/lib/postgresql/data
      - ${USERDIR}/shared:/shared
    environment:
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASS}
      POSTGRES_DB: ${DBNAME}
      TZ: ${TZ}

  # MQTT broker
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "8883:8883"
      - "9001:9001"
    restart: always
    volumes:
      - ${USERDIR}/mosquitto/data:/mosquitto/data
      - ${USERDIR}/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ${USERDIR}/mosquitto/log:/mosquitto/log
      - ${USERDIR}/shared:/shared
    environment:
      TZ: ${TZ}

  # Pushing the Honeywell things to MQTT
  honeywell2mqtt:
    container_name: honeywell2mqtt
    image: chriskacerguis/honeywell2mqtt:2.0.0
    restart: always
    privileged: true
    depends_on:
      - mosquitto
    links:
      - mosquitto
    environment:
      MQTT_HOST: ${HOSTIP}
      TZ: ${TZ}

  # Home Assistant
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:latest
    restart: always
    network_mode: host
    privileged: true
    depends_on:
      - postgres
      - prometheus
      - mosquitto
    volumes:
      - ${USERDIR}/home-assistant:/config
      - ${USERDIR}/shared:/shared
    environment:
      TZ: ${TZ}
      HOSTIP: ${HOSTIP}
  
  # Prometheus
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    networks:
      - traefik_proxy
    volumes:
      - ${USERDIR}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ${USERDIR}/prometheus/data:/prometheus
    labels:
      - "traefik.enable=true"
      - "traefik.backend=prometheus"
      - "traefik.frontend.rule=Host:prometheus.${DOMAINNAME}"
      - "traefik.port=9090"
      - "traefik.docker.network=traefik_proxy"

  # Node-Blackbox Prometheus
  blackbox:
    container_name: blackbox
    image: prom/blackbox-exporter:latest
    ports:
      - "9115:9115"
    restart: always
    privileged: true

  # For HADashboard (not ready for use YET)
  # appdaemon:
  #  container_name: appdaemon
  #  image: acockburn/appdaemon:latest
  #  restart: always
  #  networks:
  #    - traefik_proxy
  #  volumes:
  #    - ${USERDIR}/dashboard:/conf:ro
  #  labels:
  #    - "traefik.enable=true"
  #    - "traefik.backend=appdaemon"
  #    - "traefik.frontend.rule=PathPrefixStrip: /dashboard"
  #    - "traefik.port=5050"
  #    - "traefik.docker.network=traefik_proxy"
  #    - "traefik.frontend.headers.SSLRedirect=true"
  #    - "traefik.frontend.headers.STSSeconds=315360000"
  #    - "traefik.frontend.headers.browserXSSFilter=true"
  #    - "traefik.frontend.headers.contentTypeNosniff=true"
  #    - "traefik.frontend.headers.forceSTSHeader=true"
  #    - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
  #    - "traefik.frontend.headers.STSIncludeSubdomains=true"
  #    - "traefik.frontend.headers.STSPreload=true"
  #    - "traefik.frontend.headers.frameDeny=true"

  # Portainer
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${USERDIR}/portainer/data:/data
    environment:
      TZ: ${TZ}
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=portainer"
      - "traefik.frontend.rule=PathPrefixStrip: /portainer"
      - "traefik.port=9000"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"

  # Heimdall
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    restart: always
    volumes:
      - ${USERDIR}/heimdall:/config
    environment:
      TZ: ${TZ}
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=heimdall"
      - "traefik.protocol=https"
      - "traefik.frontend.rule=PathPrefixStrip: /"
      - "traefik.port=443"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"

# Networks that are needed
networks:
  traefik_proxy:
    name: traefik_proxy
  default:
    driver: bridge