version: '3'

services:
  home-assistant:
    image: homeassistant/home-assistant:latest
    ports:
      - "8123:8123"
    depends_on:
      - postgres
      - influxdb
      - mosquitto
    volumes:
      - /srv/home-assistant:/config
    network_mode: "host"
    restart: always
    devices:
      - "/dev/zwave:/dev/zwave"
  
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: homeassistant
      POSTGRES_PASSWORD: homeassistant
    network_mode: "host"
  
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8883:8883"
    restart: always
    volumes:
      - /srv/certs:/certs
      - /srv/mosquitto/data:/mosquitto/data
      - /srv/mosquitto/config:/mosquitto/config
      - /srv/mosquitto/log:/mosquitto/log
    network_mode: "host"

  honeywell2mqtt:
    image: chriskacerguis/honeywell2mqtt:2.0.0
    restart: always
    depends_on:
      - mosquitto

  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
      - /srv/certs:/certs
    network_mode: "bridge"
    command: --ssl --sslcert /certs/fuzzyblender-with-ca.crt --sslkey /certs/fuzzyblender.key

volumes:
  portainer_data:
  postgres_data: