version: '3'

services:
  home-assistant:
    image: homeassistant/home-assistant:latest
    ports:
      - "8123:8123"
    depends_on:
      - postgres
      - influxdb
      - mosquitto
    volumes:
      - /srv/home-assistant:/config
    restart: always
    devices:
      - "/dev/zwave:/dev/zwave"
  
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: homeassistant
      POSTGRES_PASSWORD: homeassistant
  
  grafana:

  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
      - "8883:8883"
    restart: always
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt
      - /srv/mosquitto/data:/mosquitto/data
      - /srv/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /srv/mosquitto/log:/mosquitto/log

  honeywell2mqtt:
    image: chriskacerguis/honeywell2mqtt:2.0.0
    restart: always
    depends_on:
      - mosquitto

  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
      - /etc/letsencrypt/:/etc/letsencrypt
    network_mode: "bridge"
    command: --ssl --sslcert /etc/letsencrypt/live/fuzzyblender.com/fullchain.pem --sslkey /etc/letsencrypt/live/fuzzyblender.com/privkey.pem

volumes:
  portainer_data:
  postgres_data: