version: '3.7'

services:

  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    domainname: nuc.fuzzyblender.com
    networks:
      - home-assistant_default
      - traefik_proxy
    ports:
      - "80:80"
      - "443:443"
#      - "XXXX:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
#      - "traefik.frontend.rule=Host:traefik.fuzzyblender.com"  
      - "traefik.frontend.rule=Host:nuc.fuzzyblender.com; PathPrefixStrip: /traefik"
      - "traefik.port=8080"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
#      - "traefik.frontend.headers.STSSeconds=315360000"
#      - "traefik.frontend.headers.browserXSSFilter=true"
#      - "traefik.frontend.headers.contentTypeNosniff=true"
#      - "traefik.frontend.headers.forceSTSHeader=true"
#      - "traefik.frontend.headers.SSLHost=nuc.fuzzyblender.com"
#      - "traefik.frontend.headers.STSIncludeSubdomains=true"
#      - "traefik.frontend.headers.STSPreload=true"
#      - "traefik.frontend.headers.frameDeny=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /srv/traefik:/etc/traefik
      - /srv/certs:/srv/certs
  
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:latest
    network_mode: host
    restart: always
    depends_on:
      - postgres
      - influxdb
      - mosquitto
    volumes:
      - /srv/home-assistant:/config
      - /srv/certs:/srv/certs
    
  postgres:
    container_name: postgres
    image: postgres:alpine
    network_mode: host
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /srv/certs:/srv/certs
    environment:
      POSTGRES_USER: homeassistant
      POSTGRES_PASSWORD: homeassistant
  
  mosquitto:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    network_mode: host
    restart: always
    volumes:
      - /srv/certs:/srv/certs
      - /srv/mosquitto/data:/mosquitto/data
      - /srv/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - /srv/mosquitto/log:/mosquitto/log

  honeywell2mqtt:
    container_name: honeywell2mqtt
    image: chriskacerguis/honeywell2mqtt:2.0.0
    restart: always
    privileged: true
    depends_on:
      - mosquitto
    environment:
      MQTT_HOST: 1.1.1.1

  influxdb:
    container_name: influxdb
    image: influxdb:alpine
    network_mode: host
    restart: always
    volumes:
      - influxdb_data:/var/lib/influxdb
      - /srv/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - /srv/certs:/srv/certs
    environment:
      INFLUXDB_DB: home_assistant

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    network_mode: host
    restart: always
    user: root
    volumes:
      - /srv/grafana/data:/var/lib/grafana
      - /srv/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - /srv/certs:/srv/certs

  adminer:
    container_name: adminder
    image: adminer
    restart: always
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=adminer"
#      - "traefik.frontend.rule=Host:traefik.fuzzyblender.com"  
      - "traefik.frontend.rule=Host:nuc.fuzzyblender.com; PathPrefixStrip: /adminer"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
#      - "traefik.frontend.headers.STSSeconds=315360000"
#      - "traefik.frontend.headers.browserXSSFilter=true"
#      - "traefik.frontend.headers.contentTypeNosniff=true"
#      - "traefik.frontend.headers.forceSTSHeader=true"
#      - "traefik.frontend.headers.SSLHost=nuc.fuzzyblender.com"
#      - "traefik.frontend.headers.STSIncludeSubdomains=true"
#      - "traefik.frontend.headers.STSPreload=true"
#      - "traefik.frontend.headers.frameDeny=true"

  glances:
    container_name: glances
    image: nicolargo/glances
    restart: always
    networks:
      - traefik_proxy
    pid: host
#    ports:
#      - "61208:61208"
#      - "61209:61209"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      GLANCES_OPT: -w
    labels:
      - "traefik.enable=true"
      - "traefik.backend=glances"
#      - "traefik.frontend.rule=Host:traefik.fuzzyblender.com"  
      - "traefik.frontend.rule=Host:nuc.fuzzyblender.com; PathPrefixStrip: /glances"
      - "traefik.port=61208"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
#      - "traefik.frontend.headers.STSSeconds=315360000"
#      - "traefik.frontend.headers.browserXSSFilter=true"
#      - "traefik.frontend.headers.contentTypeNosniff=true"
#      - "traefik.frontend.headers.forceSTSHeader=true"
#      - "traefik.frontend.headers.SSLHost=nuc.fuzzyblender.com"
#      - "traefik.frontend.headers.STSIncludeSubdomains=true"
#      - "traefik.frontend.headers.STSPreload=true"
#      - "traefik.frontend.headers.frameDeny=true"

  homebridge:
    container_name: homebridge
    image: oznu/homebridge
    network_mode: host
    restart: always
    volumes:
      - /srv/homebridge:/homebridge
      - /srv/certs:/srv/certs
    environment:
      TZ: America/Chicago
      HOMEBRIDGE_CONFIG_UI: 1
      HOMEBRIDGE_CONFIG_UI_PORT: 8888
  
# Generally speaking, I usually setup Portainer by itself
#  portainer:
#    image: portainer/portainer
#    network_mode: host
#    restart: always
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - portainer_data:/data
#      - /srv/certs:/srv/certs
#    network_mode: "bridge"
#    command: --ssl --sslcert /srv/certs/fullchain.crt --sslkey /srv/certs/fuzzyblender.key

volumes:
  postgres_data:
    name: postgres_data
  influxdb_data:
    name: influxdb_data
#  portainer_data:

networks:
  traefik_proxy:
    name: traefik_proxy
  default:
    driver: bridge