version: '3.7'

services:

  # Traefik Reverse Proxy
  traefik:
    image: traefik:alpine
    container_name: traefik
    domainname: ${DOMAINNAME}
    restart: always
    networks:
      - default
      - traefik_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${USERDIR}/traefik:/etc/traefik
      - ${USERDIR}/shared:/shared

  postgres:
    container_name: postgres
    image: postgres:alpine
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ${USERDIR}/postgres:/var/lib/postgresql/data
      - ${USERDIR}/shared:/shared
    environment:
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASS}
      POSTGRES_DB: ${DBNAME}
      TZ: ${TZ}

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "8883:8883"
      - "9001:9001"
    restart: always
    volumes:
      - ${USERDIR}/mosquitto/data:/mosquitto/data
      - ${USERDIR}/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ${USERDIR}/mosquitto/log:/mosquitto/log
      - ${USERDIR}/shared:/shared
    environment:
      TZ: ${TZ}

  honeywell2mqtt:
    container_name: honeywell2mqtt
    image: chriskacerguis/honeywell2mqtt:2.0.0
    restart: always
    privileged: true
    depends_on:
      - mosquitto
    links:
      - mosquitto
    environment:
      MQTT_HOST: ${HOSTIP}
      TZ: ${TZ}

  influxdb:
    container_name: influxdb
    image: influxdb:alpine
    ports:
      - "8086:8086"
    restart: always
    volumes:
      - ${USERDIR}/influxdb:/var/lib/influxdb
      - ${USERDIR}/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ${USERDIR}/shared:/shared
    environment:
      INFLUXDB_DB: ${DBNAME}
      INFLUXDB_USER: ${DBUSER}
      INFLUXDB_USER_PASSWORD: ${DBPASS}
      TZ: ${TZ}
  
  # Below are things behind Traefik

  # Home Assistant
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:latest
    restart: always
    networks:
      - traefik_proxy
    depends_on:
      - postgres
      - influxdb
      - mosquitto
    volumes:
      - ${USERDIR}/home-assistant:/config
      - ${USERDIR}/shared:/shared
    labels:
      - "traefik.enable=true"
      - "traefik.backend=homeassistant"
      - "traefik.frontend.rule=Host:ha.${DOMAINNAME}"  
      - "traefik.port=8123"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
    environment:
      TZ: ${TZ}
      HOSTIP: ${HOSTIP}

  # Glances - Keep an eye on things
  glances:
    container_name: glances
    image: nicolargo/glances:latest-alpine
    restart: always
    networks:
      - traefik_proxy
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      GLANCES_OPT: -w
    labels:
      - "traefik.enable=true"
      - "traefik.backend=glances"
      - "traefik.frontend.rule=PathPrefixStrip: /glances"
      - "traefik.port=61208"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"

  # Nagios for monitoring
  # Serving from local drive in case the NAS fails
  nagios:
    container_name: nagios
    image: jasonrivers/nagios:latest
    restart: always
    networks:
      - traefik_proxy
    volumes:
      - /srv/nagios:/opt/nagios/etc
    labels:
      - "traefik.enable=true"
      - "traefik.backend=nagios"
      - "traefik.frontend.rule=PathPrefixStrip: /nagios"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
#      - "traefik.frontend.headers.frameDeny=true"

  # For HADashboard (not ready for use YET)
  # appdaemon:
  #  container_name: appdaemon
  #  image: acockburn/appdaemon:latest
  #  restart: always
  #  networks:
  #    - traefik_proxy
  #  volumes:
  #    - ${USERDIR}/dashboard:/conf:ro
  #  labels:
  #    - "traefik.enable=true"
  #    - "traefik.backend=appdaemon"
  #    - "traefik.frontend.rule=PathPrefixStrip: /dashboard"
  #    - "traefik.port=5050"
  #    - "traefik.docker.network=traefik_proxy"
  #    - "traefik.frontend.headers.SSLRedirect=true"
  #    - "traefik.frontend.headers.STSSeconds=315360000"
  #    - "traefik.frontend.headers.browserXSSFilter=true"
  #    - "traefik.frontend.headers.contentTypeNosniff=true"
  #    - "traefik.frontend.headers.forceSTSHeader=true"
  #    - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
  #    - "traefik.frontend.headers.STSIncludeSubdomains=true"
  #    - "traefik.frontend.headers.STSPreload=true"
  #    - "traefik.frontend.headers.frameDeny=true"

  # Portainer - WebUI for Containers
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${USERDIR}/portainer/data:/data
    environment:
      TZ: ${TZ}
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=portainer"
      - "traefik.frontend.rule=PathPrefixStrip: /portainer"
      - "traefik.port=9000"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"

# Networks that are needed
networks:
  traefik_proxy:
    name: traefik_proxy
  default:
    driver: bridge