title: Home
views:
  - icon: mdi:home-assistant
    title: Environment
    cards:
      - type: gauge
        title: Alergy Index
        unit_of_measurement: ''
        max: 12
        entity: sensor.allergy_index_today
        severity:
          green: 0
          yellow: 4.8
          red: 7.3