#-------------------------------------------
# Front Door Opened
#-------------------------------------------
- alias: "Front Door Opened Notice"
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.front_door
      from: 'closed'
      to: 'open'
  condition:
    condition: state
    entity_id: group.family
    state: 'not_home'
  action:
    - service: notify.sms
      data_template:
        message: "\U0001F6AA {{ trigger.to_state.attributes.friendly_name }} has been opened"
        target:
          - !secret chris_mobile_num
