- platform: ping
  host: 192.168.128.236
  name: Garage Right Camera

- platform: ping
  host: 192.168.128.240
  name: Garage Left Camera

- platform: ping
  host: 192.168.128.227
  name: Megan Open Garage

- platform: ping
  host: 192.168.128.248
  name: Chris Open Garage

- platform: ping
  host: 192.168.128.222
  name: Rachio Panel

- platform: ping
  host: 192.168.128.235
  name: Craft Room Probe

- platform: ping
  host: 192.168.128.234
  name: Laundry Room Probe

