#-------------------------------------------
#  Binary Sensors
#-------------------------------------------
- platform: template
  sensors:
    all_doors:
      friendly_name: "All Doors"
      device_class: opening
      value_template: >-
        {%- if is_state("binary_sensor.garage_door", "on")
            or is_state("binary_sensor.front_door", "on")
            or is_state("binary_sensor.back_door", "on") -%}
        True
        {%- else -%}
        False
        {%- endif %}

#-------------------------------------------
- platform: template
  sensors: 
    all_locks:
      friendly_name: "All Locks"
      device_class: opening
      value_template: >-
        {%- if is_state("lock.garage_door_locked", "unlocked")
            or is_state("lock.front_door_locked", "unlocked")
            or is_state("lock.back_door_locked", "unlocked") -%}
        True
        {%- else -%}
        False
        {%- endif %}

#-------------------------------------------
- platform: template
  sensors: 
    all_windows:
      friendly_name: "All Windows"
      device_class: opening
      value_template: >-
        {%- if is_state("binary_sensor.back_right_window", "on")
            or is_state("binary_sensor.back_window_one", "on")
            or is_state("binary_sensor.back_window_three", "on")
            or is_state("binary_sensor.front_window_two", "on")
            or is_state("binary_sensor.front_window_one", "on")
            or is_state("binary_sensor.front_right_window", "on")
            or is_state("binary_sensor.child_window", "on")
            or is_state("binary_sensor.back_window_two", "on")
            or is_state("binary_sensor.guest_window", "on")
            or is_state("binary_sensor.kitchen_sink_window", "on")
            or is_state("binary_sensor.master_bathroom_window", "on")
            or is_state("binary_sensor.master_bedroom_window", "on")
            or is_state("binary_sensor.study_window", "on") -%}
        True
        {%- else -%}
        False
        {%- endif %}

#-------------------------------------------
- platform: template
  sensors:
    all_covers:
      friendly_name: "All Covers"
      device_class: opening
      value_template: >-
        {%- if is_state("cover.chris_overhead_garage_door", "open") -%}
        True
        {%- else -%}
        False
        {%- endif %}

#-------------------------------------------
#- platform: template
#  sensors: 
#    all_windows:
#      friendly_name: "All Honeywell Heartbeat Ok"
#      device_class: opening
#      value_template: >-
#        {%- if is_state("binary_sensor.study_window_heartbeat", "unknown")
#            or is_state("binary_sensor.back_window_one", "on")
#            or is_state("binary_sensor.back_window_three", "on")
#            or is_state("binary_sensor.front_window_two", "on")
#            or is_state("binary_sensor.front_window_one", "on")
#            or is_state("binary_sensor.front_right_window", "on")
#            or is_state("binary_sensor.child_window", "on")
#            or is_state("binary_sensor.back_window_two", "on")
#            or is_state("binary_sensor.guest_window", "on")
#            or is_state("binary_sensor.kitchen_sink_window", "on")
#            or is_state("binary_sensor.master_bathroom_window", "on")
#            or is_state("binary_sensor.master_bedroom_window", "on")
#            or is_state("binary_sensor.study_window", "on") -%}
#        False
#        {%- else -%}
#        True
#        {%- endif %}       