#-------------------------------------------
#  Binary Sensors
#-------------------------------------------
- platform: template
  sensors:
    all_doors:
      friendly_name: "All Doors"
      device_class: opening
      value_template: >-
        {%- if is_state("binary_sensor.garage_door", "off")
            and is_state("binary_sensor.front_door", "off")
            and is_state("binary_sensor.back_door", "off") -%}
        off
        {%- else -%}
        on
        {%- endif %}

#-------------------------------------------
- platform: template
  sensors: 
    all_locks:
      friendly_name: "All Locks"
      device_class: opening
      value_template: >-
        {%- if is_state("lock.garage_door_locked", "locked")
            and is_state("lock.front_door_locked", "locked")
            and is_state("lock.back_door_locked", "locked") -%}
        off
        {%- else -%}
        on
        {%- endif %}

#-------------------------------------------
- platform: template
  sensors: 
    all_windows:
      friendly_name: "All Windows"
      device_class: opening
      value_template: >-
        {%- if is_state("binary_sensor.back_right_window", "off")
            and is_state("binary_sensor.back_window_one", "off")
            and is_state("binary_sensor.back_window_three", "off")
            and is_state("binary_sensor.front_window_two", "off")
            and is_state("binary_sensor.front_window_one", "off")
            and is_state("binary_sensor.front_right_window", "off")
            and is_state("binary_sensor.child_window", "off")
            and is_state("binary_sensor.back_window_two", "off")
            and is_state("binary_sensor.guest_window", "off")
            and is_state("binary_sensor.kitchen_sink_window", "off")
            and is_state("binary_sensor.master_bathroom_window", "off")
            and is_state("binary_sensor.master_bedroom_window", "off")
            and is_state("binary_sensor.study_window", "off") -%}
        off
        {%- else -%}
        on
        {%- endif %}

#-------------------------------------------
- platform: template
  sensors:
    all_covers:
      friendly_name: "All Covers"
      device_class: opening
      value_template: >-
        {%- if is_state("cover.chris_overhead_garage_door", "closed") -%}
        closed
        {%- else -%}
        open
        {%- endif %}
      entity_id:
        - cover.chris_overhead_garage_door