- platform: template
  sensors:
    study_door:
      value_template: >-
      {%- if states.sensor.sensative_strips_access_control.state == '22' -%} 
        open 
      {%- else -%} 
        closed 
      {%- endif %}
      friendly_name: 'Study Door'
      device_class: opening

# Note: 23 = door closed, 22 = door open