- platform: template
  sensors:
    study_door:
      value_template: '{{ is_state('sensor.sensative_strips_access_control', '22') }}'
      friendly_name: 'Study Door'
      device_class: opening

# Note: 23 = door closed, 22 = door open