#-------------------------------------------
# Chris's BLE Beacon
# {"id":"2f234454cf6d4a0fadf2f4911ba9ffa6_0000_0001","name":"Chris","distance":2.330905473323243}
#-------------------------------------------
- platform: mqtt_room
  device_id: 2f234454cf6d4a0fadf2f4911ba9ffa6_0000_0001
  name: 'Chris Beacon'
  state_topic: 'happy-bubbles/presence/ha'
  timeout: 5
  away_timeout: 60