#-------------------------------------------
# Megan's BLE Beacon
# {"id":"bc44f10e7b554f9984ec1949292f72f1_0000_0001","name":"Megan","distance":2.9003455293388853}
#-------------------------------------------
- platform: mqtt_room
  device_id: bc44f10e7b554f9984ec1949292f72f1_0000_0001
  name: 'Megan Beacon'
  state_topic: 'happy-bubbles/presence/ha'
  timeout: 5
  away_timeout: 60