#-------------------------------------------
#  Settings Tab
#-------------------------------------------
settings:
  name: Settings
  view: yes
  icon: mdi:settings
  entities:
    - group.all_automations
    - group.house_mode

#-------------------------------------------
house_mode:
  name: House Mode
  entities:
    - input_select.house_mode