#-------------------------------------------
#  Settings Tab
#-------------------------------------------
settings:
  name: Settings
  view: yes
  icon: mdi:settings
  entities:
    - group.all_automations
    - group.house_mode
    - group.rf_heartbeats

#-------------------------------------------
house_mode:
  name: House Mode
  entities:
    - input_select.house_mode

#-------------------------------------------
rf_heartbeats:
  name: RF Device Heartbeats
  entities:
    - sensor.back_door_heartbeat | now()
    - sensor.back_window_one_heartbeat
    - sensor.back_window_three_heartbeat
    - sensor.back_window_two_heartbeat
    - sensor.child_window_heartbeat
    - sensor.front_door_heartbeat
    - sensor.front_right_window_heartbeat
    - sensor.front_window_one_heartbeat
    - sensor.front_window_two_heartbeat
    - sensor.garage_door_heartbeat
    - sensor.guest_window_heartbeat
    - sensor.kitchen_sink_window_heartbeat
    - sensor.master_bathroom_window_heartbeat
    - sensor.master_bedroom_window_heartbeat
    - sensor.study_window_heartbeat