#-------------------------------------------
#  System Tab
#-------------------------------------------
system_tab:
  name: System
  view: yes
  icon: mdi:settings
  entities:
    - group.battery_levels
    - group.internet_speeds
    - group.ups
    - group.all_automations
    - group.camera_status

camera_status:
  name: Camera Status
  entities:
     - binary_sensor.deck_camera_status
     - binary_sensor.driveway_camera_status
     - binary_sensor.front_yard_camera_status
     - binary_sensor.garage_camera_status
     - binary_sensor.porch_camera_status
