- platform: template
  sensors:
    all_windows:
      friendly_name: "All Windows"
      value_template: >-
        {% if is_state('sensor.study_window', 'closed')
            and is_state('sensor.master_bathroom_window', 'closed')
            and is_state('sensor.guest_window', 'closed')
            and is_state('sensor.child_window', 'closed')
            and is_state('sensor.front_right_window', 'closed')
            and is_state('sensor.front_window_one', 'closed')
            and is_state('sensor.front_window_two', 'closed')
            and is_state('sensor.back_window_one', 'closed')
            and is_state('sensor.back_window_two', 'closed')
            and is_state('sensor.back_window_three', 'closed')
            and is_state('sensor.back_right_window', 'closed')
            and is_state('sensor.kitchen_sink_window', 'closed')
            and is_state('sensor.master_bedroom_window', 'closed') %}
          closed
        {% else %}
          open
        {% endif %}