- platform: mqtt
  state_topic: "home/sensors/3a002d000247363333343435/humidity"
  device_class: humidity
  name: "Study Humidity"
  unit_of_measurement: '%'

- platform: mqtt
  state_topic: "home/sensors/3a002d000247363333343435/temp"
  device_class: temperature
  name: "Study Temp"
  unit_of_measurement: '°F'