#-------------------------------------------
#  Average Temp
#-------------------------------------------
- platform: min_max
  name: Average Temperature
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.wirelesstag_clara_room_temperature
    - sensor.wirelesstag_guest_room_temperature
    - sensor.wirelesstag_kitchen_temperature
    - sensor.wirelesstag_masterbed_temperature
    - sensor.wirelesstag_play_area_temperature
    - sensor.wirelesstag_study_temperature
    - sensor.wirelesstag_master_bath_temperature

#-------------------------------------------
#  Average Humidity
#-------------------------------------------
- platform: min_max
  name: Average Humidity
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.wirelesstag_clara_room_humidity
    - sensor.wirelesstag_guest_room_humidity
    - sensor.wirelesstag_kitchen_humidity
    - sensor.wirelesstag_masterbed_humidity
    - sensor.wirelesstag_play_area_humidity
    - sensor.wirelesstag_study_humidity