- platform: darksky
  api_key: !secret darksky_api_key
  monitored_conditions:
    - summary
    - icon
    - nearest_storm_distance
    - precip_probability
    - precip_intensity
    - wind_speed
    - wind_bearing
    - apparent_temperature
    - pressure
    - humidity
    - temperature