#-------------------------------------------
#  Family Status
#-------------------------------------------
- platform: template
  sensors:
    family_status:
      friendly_name: 'Family Status'
      value_template: >-
        {% if is_state('sensor.chris_beacon', 'not_home') and is_state('sensor.megan_beacon', 'not_home') %}
          not_home
        {% else %}
          home
        {% endif %}
      icon_template: >-
        {% if is_state('sensor.chris_beacon', 'not_home') and is_state('sensor.megan_beacon', 'not_home') %}
          mdi:airplane
        {% else %}
          mdi:home
        {% endif %}