#-------------------------------------------
#  Heartbeat Sensors for Honeywell Sensors
#-------------------------------------------
- platform: mqtt
  name: "Study Window Heartbeat"
  state_topic: "homeassistant/sensor/honeywell"
  expire_after: 10800
  value_template: '{% if value_json.id is equalto 547651 %} {{value_json.time}} {% else %} {{states.sensor.study_window_heartbeat.state}} {% endif %}'

#-------------------------------------------
- name: "Master Bathroom Window Heartbeat"
  platform: mqtt
  state_topic: "homeassistant/sensor/honeywell"
  expire_after: 10800
  value_template: '{% if value_json.id is equalto 792500 %} {{value_json.time}} {% else %} {{states.sensor.master_bathroom_window_heartbeat.state}} {% endif %}'

#-------------------------------------------
- name: "Guest Window Heartbeat"
  platform: mqtt
  state_topic: "homeassistant/sensor/honeywell"
  expire_after: 10800
  value_template: '{% if value_json.id is equalto 871236 %} {{value_json.time}} {% else %} {{states.sensor.guest_window_heartbeat.state}} {% endif %}'

#-------------------------------------------
- name: "Child Window Heartbeat"
  platform: mqtt
  state_topic: "homeassistant/sensor/honeywell"
  expire_after: 10800
  value_template: '{% if value_json.id is equalto 265871 %} {{value_json.time}} {% else %} {{states.sensor.child_window_heartbeat.state}} {% endif %}'

#-------------------------------------------
- name: "Front Right Window Heartbeat"
  platform: mqtt
  state_topic: "homeassistant/sensor/honeywell"
  expire_after: 10800
  value_template: '{% if value_json.id is equalto 785920 %} {{value_json.time}} {% else %} {{states.sensor.front_right_window_heartbeat.state}} {% endif %}'

#-------------------------------------------
- name: "Front Window One Heartbeat"
  platform: mqtt
  state_topic: "homeassistant/sensor/honeywell"
  expire_after: 10800
  value_template: '{% if value_json.id is equalto 529823 %} {{value_json.time}} {% else %} {{states.sensor.front_window_one.state}} {% endif %}'

#-------------------------------------------
- name: "Front Window Two Heartbeat"
  platform: mqtt
  state_topic: "homeassistant/sensor/honeywell"
  expire_after: 10800
  value_template: '{% if value_json.id is equalto 4559 %} {{value_json.time}} {% else %} {{states.sensor.front_window_two.state}} {% endif %}'

#-------------------------------------------
- name: "Back Window One Heartbeat"
  platform: mqtt
  state_topic: "homeassistant/sensor/honeywell"
  expire_after: 10800
  value_template: '{% if value_json.id is equalto 272026 %} {{value_json.time}} {% else %} {{states.sensor.back_window_one.state}} {% endif %}'

#-------------------------------------------
- name: "Back Window Two Heartbeat"
  platform: mqtt
  state_topic: "homeassistant/sensor/honeywell"
  expire_after: 10800
  value_template: '{% if value_json.id is equalto 224113 %} {{value_json.time}} {% else %} {{states.sensor.back_window_two.state}} {% endif %}'

#-------------------------------------------
- name: "Back Window Three Heartbeat"
  platform: mqtt
  state_topic: "homeassistant/sensor/honeywell"
  expire_after: 10800
  value_template: '{% if value_json.id is equalto 830937 %} {{value_json.time}} {% else %} {{states.sensor.back_window_three.state}} {% endif %}'

#-------------------------------------------
- name: "Back Right Window Heartbeat"
  platform: mqtt
  state_topic: "homeassistant/sensor/honeywell"
  expire_after: 10800
  value_template: '{% if value_json.id is equalto 924316 %} {{value_json.time}} {% else %} {{states.sensor.back_right_window_heartbeat.state}} {% endif %}'

#-------------------------------------------
- name: "Kitchen Sink Window Heartbeat"
  platform: mqtt
  state_topic: "homeassistant/sensor/honeywell"
  expire_after: 10800
  value_template: '{% if value_json.id is equalto 65736 %} {{value_json.time}} {% else %} {{states.sensor.kitchen_sink_window_heartbeat.state}} {% endif %}'

#-------------------------------------------
- name: "Master Bedroom Window Heartbeat"
  platform: mqtt
  state_topic: "homeassistant/sensor/honeywell"
  expire_after: 10800
  value_template: '{% if value_json.id is equalto 761758 %} {{value_json.time}} {% else %} {{states.sensor.master_bedroom_window_heartbeat.state}} {% endif %}'

#-------------------------------------------
- name: "Front Door Heartbeat"
  platform: mqtt
  state_topic: "homeassistant/sensor/honeywell"
  expire_after: 10800
  value_template: '{% if value_json.id is equalto 648705 %} {{value_json.time}} {% else %} {{states.sensor.front_door_heartbeat.state}} {% endif %}'

#-------------------------------------------
- name: "Back Door Heartbeat"
  platform: mqtt
  state_topic: "homeassistant/sensor/honeywell"
  expire_after: 10800
  value_template: '{% if value_json.id is equalto 491009 %} {{value_json.time}} {% else %} {{as_timestamp(states.sensor.back_door_heartbeat.state) | timestamp_custom("%Y%m%d-%H%M%S")}} {% endif %}'

#-------------------------------------------
- name: "Garage Door Heartbeat"
  platform: mqtt
  state_topic: "homeassistant/sensor/honeywell"
  expire_after: 10800
  value_template: '{% if value_json.id is equalto 275843 %} {{value_json.time}} {% else %} {{states.sensor.garage_door_heartbeat.state}} {% endif %}'