- platform: mqtt
  name: "Study Window Heartbeat"
  state_topic: "homeassistant/sensor/honeywell"
  expire_after: 3600
  value_template: '{% if value_json.id is equalto 547651x %} {{value_json.time}} {% else %} {{states.sensor.study_window_heartbeat.state}} {% endif %}'