#-------------------------------------------
#  Back Door Lock
#-------------------------------------------
- platform: template
  sensors:
    back_door_battery:
      friendly_name: 'Back Door Lock Battery'
      value_template: >-
        {% if states.zwave.back_door %}
          {{ states.zwave.back_door.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
      icon_template: >-
        {% set battery_level = states('sensor.back_door_battery')|int('unknown') %}
        {% set battery_round = (battery_level|int / 10)|int * 10 %}
        {% if battery_level == 'unknown' %}
          mdi:battery-unknown
        {% else %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
        {% endif %}