#-------------------------------------------
#  Speedtest Sensor
#-------------------------------------------
- platform: fastdotcom

#-------------------------------------------
#  Monitor Synology NAS UPS
#-------------------------------------------
- platform: nut
  name: Synology
  host: 192.168.1.34
  resources:
    - ups.load
    - battery.runtime
    - battery.charge
    - ups.status