#-------------------------------------------
#  Cluster Sensor Prototype
#-------------------------------------------
- platform: mqtt
  name: Office Temp
  state_topic: "v1/devices/temp"
  value_template: '{% if value_json.id is equalto 111 %} {{value_json.temperature}} {% else %} {{states.sensor.office_temp.state}} {% endif %}'

- platform: mqtt
  name: Office Humidity
  state_topic: "v1/devices/temp"
  value_template: '{% if value_json.id is equalto 111 %} {{value_json.humidity}} {% else %} {{states.sensor.office_humidity.state}} {% endif %}'