#-------------------------------------------
#  Laundry Room Motion Sensor
#-------------------------------------------
- platform: template
  sensors:
    laundry_multisensor_motion:
      friendly_name: 'Laundry MultiSensor Motion'
      value_template: >-
        {% if is_state('sensor.laundry_multisensor_burglar', '8') %}
          motion
        {% elif is_state('sensor.laundry_multisensor_burglar', '3') %}
          tamper
        {% else %}
          still
        {% endif %}

#-------------------------------------------
#  Master Bath Motion Sensor
#-------------------------------------------
- platform: template
  sensors:
    master_bath_multisensor_motion:
      friendly_name: 'Master Bath MultiSensor Motion'
      value_template: >-
        {% if is_state('sensor.master_bath_multisensor_burglar', '8') %}
          motion
        {% elif is_state('sensor.master_bath_multisensor_burglar', '3') %}
          tamper
        {% else %}
          still
        {% endif %}

#-------------------------------------------
#  Study Motion Sensor
#-------------------------------------------
- platform: template
  sensors:
    study_multisensor_motion:
      friendly_name: 'Study MultiSensor Motion'
      value_template: >-
        {% if is_state('sensor.study_multisensor_burglar', '8') %}
          motion
        {% elif is_state('sensor.study_multisensor_burglar', '3') %}
          tamper
        {% else %}
          still
        {% endif %}

#-------------------------------------------
#  Kitchen Motion Sensor
#-------------------------------------------
- platform: template
  sensors:
    kitchen_multisensor_motion:
      friendly_name: 'Kitchen MultiSensor Motion'
      value_template: >-
        {% if is_state('sensor.kitchen_multisensor_burglar', '8') %}
          motion
        {% elif is_state('sensor.kitchen_multisensor_burglar', '3') %}
          tamper
        {% else %}
          still
        {% endif %}