#-------------------------------------------
# OpenGarage Sensors (Megan)
#-------------------------------------------
- platform: template
  sensors:
    megan_overhead_garage_door:
      friendly_name: 'Megan Overhead Garage Status'
      value_template: '{% if states.cover.megan_overhead_garage_door %}
          {% if states.cover.megan_overhead_garage_door.attributes["door_state"] == "open" %}
            Open
          {% elif states.cover.megan_overhead_garage_door.attributes["door_state"] == "closed" %}
            Closed
          {% elif states.cover.megan_overhead_garage_door.attributes["door_state"] == "opening" %}
            Opening
          {% elif states.cover.megan_overhead_garage_door.attributes["door_state"] == "closing" %}
            Closing
          {% else %}
            Unknown
          {% endif %}
          {% else %}
          n/a
          {% endif %}'

#-------------------------------------------
- platform: template
  sensors:
    megan_car_present:
      friendly_name: 'Infinity in Garage'
      value_template: '{% if states.cover.megan_overhead_garage_door %}
          {% if states.cover.megan_overhead_garage_door.state == "open" %}
            Door Open / Unknown
          {% elif ((states.cover.megan_overhead_garage_door.attributes["distance_sensor"] > 100) and (states.cover.megan_overhead_garage_door.attributes["distance_sensor"] < 120)) %}
            Yes
          {% else %}
            No
          {% endif %}
          {% else %}
          n/a
          {% endif %}'


#-------------------------------------------
# OpenGarage Sensors (Chris)
#-------------------------------------------
- platform: template
  sensors:
    chris_overhead_garage_door:
      friendly_name: 'Chris Overhead Garage Status'
      value_template: '{% if states.cover.megan_overhead_garage_door %}
          {% if states.cover.chris_overhead_garage_door.attributes["door_state"] == "open" %}
            Open
          {% elif states.cover.chris_overhead_garage_door.attributes["door_state"] == "closed" %}
            Closed
          {% elif states.cover.chris_overhead_garage_door.attributes["door_state"] == "opening" %}
            Opening
          {% elif states.cover.chris_overhead_garage_door.attributes["door_state"] == "closing" %}
            Closing
          {% else %}
            Unknown
          {% endif %}
          {% else %}
          n/a
          {% endif %}'

#-------------------------------------------
- platform: template
  sensors:
    chris_car_present:
      friendly_name: 'Rogue in Garage'
      value_template: '{% if states.cover.chris_overhead_garage_door %}
          {% if states.cover.chris_overhead_garage_door.state == "open" %}
            Door Open / Unknown
          {% elif ((states.cover.chris_overhead_garage_door.attributes["distance_sensor"] > 100) and (states.cover.chris_overhead_garage_door.attributes["distance_sensor"] < 120)) %}
            Yes
          {% else %}
            No
          {% endif %}
          {% else %}
          n/a
          {% endif %}'