#-------------------------------------------
# OpenGarage Sensors
#-------------------------------------------
- platform: template
  sensors:
    chris_overhead_garage_door:
      friendly_name: 'Chris Overhead Garage Status'
      value_template: '{% if states.cover.chris_overhead_garage_door %}
          {% if states.cover.chris_overhead_garage_door.attributes["door_state"] == "open" %}
            Open
          {% elif states.cover.chris_overhead_garage_door.attributes["door_state"] == "closed" %}
            Closed
          {% elif states.cover.chris_overhead_garage_door.attributes["door_state"] == "opening" %}
            Opening
          {% elif states.cover.chris_overhead_garage_door.attributes["door_state"] == "closing" %}
            Closing
          {% else %}
            Unknown
          {% endif %}
          {% else %}
          n/a
          {% endif %}'

#-------------------------------------------
- platform: template
  sensors:
    chris_car_present:
      friendly_name: 'Nissan in Garage'
      value_template: '{% if states.cover.chris_overhead_garage_door %}
          {% if states.cover.chris_overhead_garage_door.state == "open" %}
            Unknown
          {% elif ((states.cover.chris_overhead_garage_door.attributes["distance_sensor"] > 40) and (states.cover.chris_overhead_garage_door.attributes["distance_sensor"] < 100)) %}
            Yes
          {% else %}
            No
          {% endif %}
          {% else %}
          n/a
          {% endif %}'