#-------------------------------------------
#  Pollen.com Sensor
#-------------------------------------------
- platform: pollen
  zip_code: !secret home_zip
  monitored_conditions:
    - allergy_average_forecasted
    - allergy_average_historical
    - allergy_index_today
    - allergy_index_tomorrow
    - allergy_index_yesterday
    - disease_average_forecasted