#-------------------------------------------
#  Monitor Synology NAS UPS
#-------------------------------------------
- platform: nut
  name: Synology
  host: 192.168.7.3
  resources:
    - ups.load
    - battery.runtime
    - battery.charge
    - ups.status