- platform: template
  sensors:
    all_doors:
      friendly_name: "All Doors"
      device_class: opening
      value_template: >-
        {{ is_state('binary_sensor.front_door', 'closed')
            and is_state('binary_sensor.back_door', 'closed')
            and is_state('binary_sensor.garage_door', 'closed') }}