- platform: template
  sensors:
    all_windows:
      friendly_name: "All Windows"
      device_class: opening
      value_template: >-
        {{ is_state('binary_sensor.study_window', 'Off')
            and is_state('binary_sensor.master_bathroom_window', 'Off')
            and is_state('binary_sensor.guest_window', 'Off')
            and is_state('binary_sensor.child_window', 'Off')
            and is_state('binary_sensor.front_right_window', 'Off')
            and is_state('binary_sensor.front_window_one', 'Off')
            and is_state('binary_sensor.front_window_two', 'Off')
            and is_state('binary_sensor.back_window_one', 'Off')
            and is_state('binary_sensor.back_window_two', 'Off')
            and is_state('binary_sensor.back_window_three', 'Off')
            and is_state('binary_sensor.back_right_window', 'Off')
            and is_state('binary_sensor.kitchen_sink_window', 'Off')
            and is_state('binary_sensor.master_bedroom_window', 'Off') }}