- platform: template
  sensors:
    all_doors:
      friendly_name: "All Doors"
      value_template: >-
        {% if is_state('sensor.front_door', 'closed') 
           and is_state('sensor.back_door', 'closed') 
           and is_state('sensor.laundry_door', 'closed') %}
        off
        {% else %}
        on
        {% endif %}
      device_class: door