- platform: template
  sensors:
    all_doors:
      friendly_name: "All Doors"
      device_class: opening
      value_template: >-
        {{ is_state('sensor.front_door', 'closed')
            and is_state('sensor.back_door', 'closed')
            and is_state('sensor.laundry_door', 'closed') }}