- platform: mqtt
  state_topic: "homeassistant/binary_sensor/chrisble"
  name: Chris iPhone Xs
  device_class: presence
  force_update: true

- platform: mqtt
  state_topic: "homeassistant/binary_sensor/meganble"
  name: Megan iPhone X
  device_class: presence
  force_update: true