#-------------------------------------------
#  Internal Monitoring
#-------------------------------------------
- platform: command_line
  name: Driveway Camera Status
  command: curl -s http://192.168.128.226 > nul && (echo "online") || (echo "offline")
  device_class: connectivity
  payload_on: "online"
  payload_off: "offline"
  scan_interval: 1800 # every 30 minutes

- platform: command_line
  name: Deck Camera Status
  command: curl -s http://192.168.128.227 > nul && (echo "online") || (echo "offline")
  device_class: connectivity
  payload_on: "online"
  payload_off: "offline"
  scan_interval: 1800 # every 30 minutes

- platform: command_line
  name: Front Door Camera Status
  command: curl -s http://192.168.128.241 > nul && (echo "online") || (echo "offline")
  device_class: connectivity
  payload_on: "online"
  payload_off: "offline"
  scan_interval: 1800 # every 30 minutes

- platform: command_line
  name: Front Yard Camera Status
  command: curl -s http://192.168.128.237 > nul && (echo "online") || (echo "offline")
  device_class: connectivity
  payload_on: "online"
  payload_off: "offline"
  scan_interval: 1800 # every 30 minutes

- platform: command_line
  name: Garage Camera Status
  command: curl -s http://192.168.128.249 > nul && (echo "online") || (echo "offline")
  device_class: connectivity
  payload_on: "online"
  payload_off: "offline"
  scan_interval: 1800 # every 30 minutes

# todo, monitor door bell device!