- platform: template
  sensors:
    garage_doors:
      friendly_name: "Garage Doors"
      value_template: >-
        {% if is_state('binary_sensor.overhead_garage_one_sensor', 'off')
            and is_state('binary_sensor.overhead_garage_two_sensor', 'off') %}
        off
        {% else %}
        on
        {% endif %}
      device_class: garage_door