- platform: template
  sensors:
    garage_doors:
      friendly_name: "Garage Doors"
      value_template: >-
        {{ is_state('binary_sensor.overhead_garage_one_sensor', 'on')
            and is_state('binary_sensor.overhead_garage_two_sensor', 'on') }}
      device_class: garage_door