- platform: template
  sensors:
    garage_doors:
      friendly_name: "Garage Doors"
      value_template: >-
        {% if not is_state('binary_sensor.overhead_garage_one_sensor', 'on')
            and not is_state('binary_sensor.overhead_garage_two_sensor', 'on') %}
        off
        {% else %}
        on
        {% endif %}
      device_class: garage_door