#-------------------------------------------
# Goodnight
#-------------------------------------------
- alias: 'Goodnight'
  initial_state: true
  hide_entity: true
  trigger:
    platform: time
    at: '22:30:00'
  action:
    - service: lock.lock
      data:
        entity_id: group.all_locks
    - service: switch.turn_on
      data:
        entity_id: switch.outside_security_switch
    - service: switch.turn_off
      data:
        entity_id: switch.kitchen_island_switch
    - service: notify.pushover_chris
      data:
        title: "\U0001F307 Goodnight Mode"
        message: "Goodnight mode has been activated by Home Assistant."
        data:
          sound: pianobar
          priority: -1