#-------------------------------------------
# Bedtime Actions
#-------------------------------------------
- alias: 'Bedtime'
  initial_state: true
  hide_entity: true
  trigger:
    platform: time
    at: '20:00:00'
  action:
    - service: switch.turn_off
      data:
        entity_id:
          - switch.study_overhead_switch
    - service: light.turn_on
      data:
        entity_id: 
          - light.study_cans_level
        brightness: 50
    - service: notify.pushover_chris
      data:
        title: "\U0001F307 Bedtime Mode"
        message: "Bedtime mode has been activated by Home Assistant."
        data:
          sound: pianobar
          priority: -1