#-------------------------------------------
# Sunset Actions
#-------------------------------------------
- alias: 'Sunset'
  initial_state: true
  hide_entity: true
  trigger:
    platform: sun
    event: sunset
  action:
    - service: switch.turn_on
      data:
        entity_id:
          - switch.front_yard_switch
          - switch.chris_bedside_switch
          - switch.megan_bedside_switch
          - switch.kitchen_island_switch
    - service: light.turn_on
      data:
        entity_id: 
          - light.kitchen_sink_level
        brightness: 40
    - service: lock.lock
      data:
        entity_id: group.all_locks
    - service: notify.pushover_chris
      data:
        title: "\U0001F307 Sunset Mode"
        message: "The sun has set.  Outside decorative lights are on, doors locked, and inside lights were turned on."
        data:
          sound: pianobar
          priority: -1
