#-------------------------------------------
# Weekday Morning Actions
#-------------------------------------------
- alias: 'Weekday Morning Actions'
  initial_state: true
  trigger:
    platform: time
    at: '06:30:00'
  condition:
    condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id:
          - switch.kitchen_island_switch
    - service: notify.pushover_chris
      data:
        message: "\U0001F307 Weekday Morning"
        title: "It's a weekday morning, and it's time to wake up."
        data:
          sound: pianobar
          priority: -1