#-------------------------------------------
# Overhead Garage Door Opened Notice
#-------------------------------------------
- alias: "Garage Door 1 Opened"
  initial_state: true
  hide_entity: true
  trigger:
    - platform: state
      entity_id: cover.garage_door_opener_1
      from: 'closed'
      to: 'open'
  action:
    - service: notify.email
      data_template:
        title: "\U0001F697 Garage Door 1 Opened"
        message: "Hi! Garage Door 1 has been opened."

#-------------------------------------------
# Overhead Garage Door Opened Notice
#-------------------------------------------
- alias: "Garage Door 2 Opened"
  initial_state: true
  hide_entity: true
  trigger:
    - platform: state
      entity_id: cover.garage_door_opener_2
      from: 'closed'
      to: 'open'
  action:
    - service: notify.email
      data_template:
        title: "\U0001F697 Garage Door 2 Opened"
        message: "Hi! Garage Door 2 has been opened."