#-------------------------------------------
# Overhead Garage Door Opened Notice
#-------------------------------------------
- alias: "Overhead Garage Door Opened"
  initial_state: true
  hide_entity: true
  trigger:
    - platform: state
      entity_id: cover.garage_door_opener_1
      from: 'closed'
      to: 'open'
    - platform: state
      entity_id: cover.garage_door_opener_2
      from: 'closed'
      to: 'open'
  action:
    - service: notify.email
      data_template:
        title: "\U0001F697 {{ trigger.to_state.attributes.friendly_name }} has been opened"
        message: "{{ trigger.to_state.attributes.friendly_name }} has been opened"
