#-------------------------------------------
# Turn on Entry Light when door opens at night
#-------------------------------------------
- alias: 'Turn on Entry Light when door opens at night'
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.front_door
    from: 'off'
    to: 'on'
  condition:
    condition: sun
    after: sunset
  action:
    - service: switch.turn_on
      data:
        entity_id:
          - switch.front_entry_switch

#-------------------------------------------
# Turn off Entry Light after 7 minutes
#-------------------------------------------
- alias: 'Turn off Entry Light after 7 minutes'
  initial_state: true
  trigger:
    platform: state
    entity_id: switch.front_entry_switch
    from: 'off'
    to: 'on'
    for:
      minutes: 7
  condition:
    condition: sun
    after: sunset
  action:
    - service: switch.turn_off
      data:
        entity_id:
          - switch.front_entry_switch