- alias: 'Asleep'
  trigger:
    - platform: state
      entity_id: sensor.eight_left_sleep_stage
      from: 'awake'
      for:
        minutes: 10
    - platform: state
      entity_id: sensor.eight_right_sleep_stage
      from: 'awake'
      for:
        minutes: 10
  action:
    - service: script.asleep