#-------------------------------------------
# When Someone Falls Asleep
#-------------------------------------------
- alias: 'Asleep'
  trigger:
    - platform: state
      entity_id: sensor.eight_left_sleep_stage
      to: 'deep'
    - platform: state
      entity_id: sensor.eight_right_sleep_stage
      to: 'deep'
  action:
    - service: script.asleep