#-------------------------------------------
# When No One Is Home
#-------------------------------------------
- alias: 'Away'
  initial_state: true
  trigger:
    platform: state
    entity_id: group.family
    to: 'away'
    for:
      minutes: 10
  action:
    - service: script.away