#-------------------------------------------
# No One Home
#-------------------------------------------
- alias: 'Away Mode'
  initial_state: true
  trigger:
    platform: state
    entity_id: group.family
    to: 'not_home'
    for:
      minutes: 10
  condition:
    condition: time
    after: '06:00:00'
    before: '21:00:00'
  action:
    - service: lock.lock
      data:
        entity_id: group.all_locks
    - service: light.turn_off
    - service: switch.turn_off