#-------------------------------------------
# When No One Is Home
#-------------------------------------------
- alias: 'Away'
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.family_status
    to: 'not_home'
    for:
      minutes: 10
  action:
    - service: script.away