#-------------------------------------------
# Just before bed
#-------------------------------------------
- alias: 'Bedtime'
  initial_state: true
  hide_entity: true
  trigger:
    platform: time
    at: '22:30:00'
  action:
    - service: script.bedtime