#-------------------------------------------
# Certificate Expire Warning
#-------------------------------------------
- alias: 'Certificate Expire Warning'
  initial_state: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.ssl_certificate_expiry
      below: 30
  action:
    - service: notify.slack
      data:
        message: "\U0001F510 SSL Certificate expiring in less than 30 days!"



