#-------------------------------------------
# Chris Car Home Actions
#-------------------------------------------
- alias: 'Chris Car Arrives Home'
  initial_state: true
  trigger:
    platform: state
    entity_id: device_tracker.2018_chevrolet_equinox
    from: 'not_home'
    to: 'home'
  action:
    - service: lock.unlock
      data:
        entity_id: lock.front_door_locked