#-------------------------------------------
# Things to do when Chris gets home
#-------------------------------------------
- alias: 'Chris arrive home'
  initial_state: true
  trigger:
    platform: state
    entity_id: device_tracker.chris_iphone_x
    from: 'not_home'
    to: 'home'
  action:
    - service: lock.unlock
      data:
        entity_id: lock.front_door_locked