#-------------------------------------------
# Turn on deck back door if night / open
#-------------------------------------------
- alias: "Turn on Deck Light if Door Open"
  initial_state: true
  hide_entity: true
  trigger:
    - platform: state
      entity_id: sensor.back_door
      from: 'closed'
      to: 'open'
  condition:
    condition: sun
    after: sunset
  action:
    service: homeassistant.turn_on
    entity_id: switch.deck_flood_switch

#-------------------------------------------
# Turn off deck light after 15 min
#-------------------------------------------
- alias: "Deck Light Off After 15 min"
  initial_state: true
  hide_entity: true
  trigger:
    platform: state
    entity_id: switch.deck_flood_switch
    from: 'off'
    to: 'on'
    for:
      minutes: 15
  action:
    service: homeassistant.turn_off
    entity_id: switch.deck_flood_switch