#-------------------------------------------
# Turn on deck back door if night / open
#-------------------------------------------
- alias: "Turn on Deck Light if Door Open"
  trigger:
    - platform: state
      entity_id: binary_sensor.back_door
      to: 'on'
      from: 'off'
  condition:
    condition: sun
    after: sunset
  action:
    service: homeassistant.turn_on
    entity_id: switch.deck_flood_switch

#-------------------------------------------
# Turn off deck light after 15 min
#-------------------------------------------
- alias: "Deck Light Off After 15 min"
  trigger:
    - platform: state
      entity_id: switch.deck_flood_switch
      to: 'off'
      from: 'on'
    for:
      minutes: 15
  action:
    service: homeassistant.turn_off
    entity_id: switch.deck_flood_switch