#-------------------------------------------
# Laundry Door Unlocked
#-------------------------------------------
- alias: "Garage Door Unlocked"
  initial_state: true
  hide_entity: true
  trigger:
    - platform: state
      entity_id: lock.garage_door_locked
      from: 'locked'
      to: 'unlocked'
  condition:
    condition: state
    entity_id: group.family
    state: 'not_home'
  action:
    - service: notify.pushover_chris
      data:
        message: "\U0001F511 Laundry Door Unlocked"
        title: "The Laundry Room Door has been {{ trigger.to_state.attributes.lock_status }}"
        data:
          sound: siren
          priority: 0