#-------------------------------------------
# Front Door Opened
#-------------------------------------------
- alias: "Front Door Opened"
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.front_door
      from: 'closed'
      to: 'open'
  condition:
    condition: state
    entity_id: group.family
    state: 'not_home'
  action:
    - service: notify.email
      data_template:
        title: "\U0001F6AA The front door has been opened"
        message: "The Front Door has been opened, and no one is currently home."

#-------------------------------------------
# Front Door Unlocked
#-------------------------------------------
- alias: "Front Door Unlocked"
  initial_state: true
  hide_entity: true
  trigger:
    - platform: state
      entity_id: lock.front_door_locked
      from: 'locked'
      to: 'unlocked'
  action:
    - service: notify.email
      data_template:
        title: "\U0001F511 Front Door has been unlocked"
        message: "The Front Door has been unlocked, and no one is currently home."