#-------------------------------------------
# Doorbell Action
#-------------------------------------------
- alias: 'Doorbell Action'
  initial_state: true
  hide_entity: true
  trigger:
    platform: state
    entity_id: binary_sensor.doorbell
    to: 'on'
  action:
    - service: camera.snapshot
      data_template:
        entity_id: camera.front_door
        filename: "/config/www/snapshots/front_door_camera_{{ trigger.to_state.last_changed }}.jpg"
    - service: notify.email
      data_template:
        message: "\U0001F4A7 Doorbell!"
#    - service: notify.twilio_sms
#      data_template:
#        message: "\U0001F514 Someone is at the front door! /local/snapshots/front_door_camera_{{ trigger.to_state.last_changed|urlencode }}.jpg"
#        target:
#          - !secret chris_mobile
#          - !secret megan_mobile