#-------------------------------------------
# Doorbell Action
#-------------------------------------------
- alias: 'Doorbell Action'
  initial_state: true
  hide_entity: true
  trigger:
    platform: state
    entity_id: sensor.doorbell
    to: 'ring'
  action:
    - service: camera.snapshot
      data_template:
        entity_id: camera.front_porch
        filename: /config/www/doorbell.jpg
    - service: notify.telegram
      data:
        message: 'Someone is at the door'
        data:
          photo:
            - file: /config/www/doorbell.jpg