#-------------------------------------------
# Alert When Front Door Opened
#-------------------------------------------
- alias: "Door Opened"
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door
      to: 'on'
      from: 'off'
  action:
    - service: notify.primary_contact
      data_template:
        message: "\U0001F6AA {{ trigger.to_state.attributes.friendly_name }} has been OPENED"

#-------------------------------------------
# Alert When Chris Garage Door Opened
#-------------------------------------------
- alias: "Chris Garage Door Opened"
  trigger:
    - platform: state
      entity_id: binary_sensor.overhead_garage_one_sensor
      to: 'on'
      from: 'off'
  action:
    - service: notify.primary_contact
      data_template:
        message: "\U0001F697 {{ trigger.to_state.attributes.friendly_name }} has been OPENED"

#-------------------------------------------
# Alert When Megan Garage Door Opened
#-------------------------------------------
- alias: "Megan Garage Door Opened"
  trigger:
    - platform: state
      entity_id: binary_sensor.overhead_garage_two_sensor
      to: 'on'
      from: 'off'
  action:
    - service: notify.primary_contact
      data_template:
        message: "\U0001F697 {{ trigger.to_state.attributes.friendly_name }} has been OPENED"