- alias: "Door Opened"
  trigger:
    - platform: state
      entity_id: binary_sensor.back_door
      to: 'on'
      from: 'off'
    - platform: state
      entity_id: binary_sensor.front_door
      to: 'on'
      from: 'off'
    - platform: state
      entity_id: binary_sensor.garage_door
      to: 'on'
      from: 'off'
  action:
    - service: script.door_opened