#-------------------------------------------
# Front Door Unlocked Notice
#-------------------------------------------
- alias: "Front Door Unlocked Notice"
  initial_state: true
  hide_entity: true
  trigger:
    - platform: state
      entity_id: lock.front_door_locked
      from: 'locked'
      to: 'unlocked'
  action:
    - service: notify.sms
      data_template:
        message: "\U0001F511 {{ trigger.to_state.attributes.friendly_name }} has been unlocked"
        target:
          - !secret chris_mobile_num

#-------------------------------------------
# Back Door Unlocked Notice
#-------------------------------------------
- alias: "Back Door Unlocked Notice"
  initial_state: true
  hide_entity: true
  trigger:
    - platform: state
      entity_id: lock.back_door_locked
      from: 'locked'
      to: 'unlocked'
  condition:
    condition: state
    entity_id: group.family
    state: 'not_home'
  action:
    - service: notify.sms
      data_template:
        message: "\U0001F511 {{ trigger.to_state.attributes.friendly_name }} has been unlocked"
        target:
          - !secret chris_mobile_num

#-------------------------------------------
# Garage Door Unlocked (no alerts ATM)
#-------------------------------------------
- alias: "Garage Door Unlocked Notice"
  initial_state: true
  hide_entity: true
  trigger:
    - platform: state
      entity_id: lock.garage_door_locked
      from: 'locked'
      to: 'unlocked'
  condition:
    condition: state
    entity_id: group.family
    state: 'not_home'
  action:
    - service: notify.sms
      data_template:
        message: "\U0001F511 {{ trigger.to_state.attributes.friendly_name }} has been unlocked"
        target:
          - !secret chris_mobile_num