#-------------------------------------------
# Front Door Opened
#-------------------------------------------
- alias: "Front Door Opened Notice"
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.front_door
      from: 'closed'
      to: 'open'
  condition:
    condition: state
    entity_id: group.family
    state: 'not_home'
  action:
    - service: notify.slack
      data:
        message: "\U0001F6AA The front door has been opened"
