#-------------------------------------------
# When Someone Rings the Doorbell
#-------------------------------------------
- alias: 'Doorbell Ring'
  trigger:
    platform: state
    entity_id: binary_sensor.ring_front_door_ding
    from: 'off'
    to: 'on'
  action:
    - service: script.doorbell_ring