#-------------------------------------------
# When Someone Rings the Doorbell
#-------------------------------------------
- alias: 'Doorbell Ring'
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.ring_front_door_ding
    from: 'off'
    to: 'on'
  action:
    - service: camera.snapshot
      data:
        entity_id: camera.front_porch
        filename: '/tmp/front-door.jpg'
    - service: notify.primary_contact
      data_template:
        title: "Someone is at the Front Door!"
        data:
          file:
            path: '/tmp/front-door.jpg'