#-------------------------------------------
# When Someone Rings the Doorbell
#-------------------------------------------
- alias: 'Doorbell Ring'
  trigger:
    platform: state
    entity_id: binary_sensor.ring_front_door_ding
    from: 'off'
    to: 'on'
  action:
    - service: notify.primary_contact
      data_template:
        title: "Doorbell"
        message: "\U0001F514 Someone is at the Front Door!"
        data:
          push:
            - category: camera
              entity_id: camera.front_porch
            - category: unlock
              entity_id: lock.front_door_locked