#-------------------------------------------
# Front Door Opened
#-------------------------------------------
- alias: "Front Door Opened"
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.front_door
      from: 'closed'
      to: 'open'
  condition:
    condition: state
    entity_id: group.family
    state: 'not_home'
  action:
    - service: notify.email
      data_template:
        title: "\U0001F6AA Front Door Opened"
        message: "The Front Door has been opened, and no one is currently home."
    - service: camera.snapshot
      data_template:
        entity_id: camera.front_door
        filename: "/config/www/snapshots/front_door_open_{{ trigger.to_state.last_changed }}.jpg"

#-------------------------------------------
# Front Door Unlocked
#-------------------------------------------
- alias: "Front Door Unlocked"
  initial_state: true
  hide_entity: true
  trigger:
    - platform: state
      entity_id: lock.front_door_locked
      from: 'locked'
      to: 'unlocked'
  action:
    - service: notify.email
      data_template:
        title: "\U0001F511 Front Door Unlocked"
        message: "The Front Door has been unlocked ({{ trigger.to_state.lock_status }})."