#-------------------------------------------
# Back Door Unlocked Notice
#-------------------------------------------
- alias: "Back Door Unlocked Notice"
  initial_state: true
  hide_entity: true
  trigger:
    - platform: state
      entity_id: lock.back_door_locked
      from: 'locked'
      to: 'unlocked'
  condition:
    condition: state
    entity_id: group.family
    state: 'not_home'
  action:
    - service: notify.pushover_chris
      data:
        message: "\U0001F511 Back Door Unlocked"
        title: "The back door has been {{ trigger.to_state.attributes.lock_status }}"
        data:
          sound: siren
          priority: 0

#-------------------------------------------
# Turn on deck back door if night / open
#-------------------------------------------
- alias: "Deck Light On When Door Opened"
  initial_state: true
  hide_entity: true
  trigger:
    - platform: state
      entity_id: sensor.back_door
      from: 'closed'
      to: 'open'
  condition:
    condition: sun
    after: sunset
  action:
    service: switch.turn_on
    entity_id: switch.deck_flood_switch

#-------------------------------------------
# Turn off deck light after 15 min
#-------------------------------------------
- alias: "Deck Light Off After 15 min"
  initial_state: true
  hide_entity: true
  trigger:
    platform: state
    entity_id: switch.deck_flood_switch
    from: 'off'
    to: 'on'
    for:
      minutes: 15
  action:
    service: switch.turn_off
    entity_id: switch.deck_flood_switch