#-------------------------------------------
# Doorbell Action
#-------------------------------------------
- alias: 'Doorbell Action'
  initial_state: true
  hide_entity: true
  trigger:
    platform: state
    entity_id: binary_sensor.doorbell
    to: 'on'
  action:
    - service: camera.snapshot
      data_template:
        entity_id: camera.front_door
        filename: "/config/www/snapshots/front_door_camera_{{ trigger.to_state.last_changed }}.jpg"
    - service: notify.sms
      data_template:
        message: "\U0001F514 Someone is at the front door! https://ha.fuzzyblender.com/local/snapshots/front_door_camera_{{ trigger.to_state.last_changed|urlencode }}.jpg"
        target:
          - !secret chris_mobile
          - !secret megan_mobile
    - service: notify.pushover_chris
      data:
        title: "\U0001F514 Doorbell"
        message: "Someone is at the front door."
        data:
          sound: pushover
          priority: 2