#-------------------------------------------
# Fall alseep
#-------------------------------------------
- alias: 'Fall asleep'
  initial_state: true
  hide_entity: true
  trigger:
    - platform: state
      entity_id: sensor.eight_left_sleep_stage
      to: 'deep'
    - platform: state
      entity_id: sensor.eight_right_sleep_stage
      to: 'deep'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.front_door
        state: 'off'
      - condition: state
        entity_id: binary_sensor.garage_door
        state: 'off'
      - condition: state
        entity_id: binary_sensor.back_door
        state: 'off'
  action:
    - service: lock.lock
      data:
        entity_id: group.all_locks