#-------------------------------------------
# Guest Bath High Humidity
#-------------------------------------------
- alias: 'Guest Bath High Humidity'
  initial_state: true
  trigger:
    platform: numeric_state
    entity_id: sensor.guest_bath_multisensor_relative_humidity
    above: 57
  action:
    service: homeassistant.turn_on
    entity_id: switch.guest_bath_fan_switch

#-------------------------------------------
# Guest Bath Normal Humidity
#-------------------------------------------
- alias: 'Guest Bath Normal Humidity'
  initial_state: true
  trigger:
    platform: numeric_state
    entity_id: sensor.guest_bath_multisensor_relative_humidity
    below: 56
  action:
    service: homeassistant.turn_off
    entity_id: switch.guest_bath_fan_switch