#-------------------------------------------
# Guest Bath High Humidity
#-------------------------------------------
- alias: 'Guest Bath High Humidity'
  initial_state: true
  trigger:
    platform: numeric_state
    entity_id: sensor.guest_bath_multisensor_relative_humidity
    above: 55
  condition:
    condition: or
    - condition: state
      entity_id: switch.guest_bath_sink_switch
      state: 'on'
    - condition: state
      entity_id: switch.guest_bath_shower_switch
      state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: switch.guest_bath_fan_switch

#-------------------------------------------
# Guest Bath Normal Humidity
#-------------------------------------------
- alias: 'Guest Bath Normal Humidity'
  initial_state: true
  trigger:
    platform: numeric_state
    entity_id: sensor.guest_bath_multisensor_relative_humidity
    below: 54
  action:
    service: homeassistant.turn_off
    entity_id: switch.guest_bath_fan_switch