#-------------------------------------------
# Sends the Housekeeper an entry code
#-------------------------------------------
sensor:
  - platform: rest
    name: Pin Code
    resource: https://api.codefu.io/v1/pin
    
#-------------------------------------------
script:
  housekeeper_code_on:
    sequence:
      - service: lock.set_usercode
        data:
          node_id: 44
          code_slot: 4
        data_template:
          usercode: "{{states.sensor.pin_code.state}}"
      - service: notify.twilio_sms
        data:
          message: "You can use the code {{ states.sensor.pin_code.state }} to get into the house today for Chris and Megan's House"
          target:
            - !secret housekeeper_mobile_num
      - service: notify.default_notifier
        data:
          message: "Housekeeper code enabled, it is: {{ states.sensor.pin_code.state }}"
  
#-------------------------------------------
  housekeeper_code_off:
    sequence:
      - service: lock.set_usercode
        data:
          node_id: 44
          code_slot: 4
          usercode: "{{states.sensor.pin_code.state}}"
      - service: notify.default_notifier
        data:
          message: "Housekeeper code disabled"

#-------------------------------------------
automation:
  - alias: Allow housekeeper entry
    trigger:
      platform: time
      at: '09:00:00'
    condition:
      - condition: time
        weekday:
          - wed
    action:
      - service: script.housekeeper_code_on

#-------------------------------------------
  - alias: Deny housekeeper entry
    trigger:
      platform: time
      at: '17:00:00'
    condition:
      - condition: time
        weekday:
          - wed
    action:
      - service: script.housekeeper_code_off