#-------------------------------------------
# No One Home
#-------------------------------------------
- alias: 'No One Home'
  initial_state: true
  hide_entity: true
  trigger:
    platform: state
    entity_id: group.family
    to: 'not_home'
    for:
      minutes: 10
  condition:
    condition: and
    conditions:
      - condition: time
        after: '06:00:00'
        before: '20:00:00'
      - condition:
        condition: state
        entity_id: input_boolean.enable_alerts
        state: 'on'
  action:
    - service: lock.lock
      data:
        entity_id: group.all_locks
    - service: light.turn_off
    - service: switch.turn_off
    - service: notify.email
      data_template:
        title: "\U0001F697 No one home, going dormant"
        message: "There is no one at home; locking doors and turning off lights."