#-------------------------------------------
# Too Humid
#-------------------------------------------
- alias: "Too Humid Alert"
  initial_state: true
  hide_entity: true
  trigger:
    platform: numeric_state
    entity_id: sensor.average_humidity
    above: 55
    for:
      minutes: 30
  action:
    - service: notify.slack
      data:
        message: "\U0001F4A7 Average house humidity is at or above 56%"