#-------------------------------------------
# Too Humid
#-------------------------------------------
- alias: "Too Humid Alert"
  initial_state: true
  hide_entity: true
  trigger:
    platform: numeric_state
    entity_id: sensor.average_humidity
    above: 65
    for:
      minutes: 60
  action:
    - service: notify.twilio_sms
      data_template:
        message: "\U0001F4A7 The average house humidity is at or above 65%"
        target:
          - !secret chris_mobile
          - !secret megan_mobile