#-------------------------------------------
# Laundry Door Unlocked
#-------------------------------------------
- alias: "Garage Door Unlocked"
  initial_state: true
  hide_entity: true
  trigger:
    - platform: state
      entity_id: lock.garage_door_locked
      from: 'locked'
      to: 'unlocked'
  condition:
    condition: state
    entity_id: group.family
    state: 'not_home'
  action:
    - service: notify.slack
      data:
        message: "\U0001F511 Laundry Door has been unlocked"

#-------------------------------------------
# Laundry Room Motion
#-------------------------------------------
- alias: 'Laundry Room Motion'
  hide_entity: true
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.laundry_multisensor_burglar
    from: '0'
    to: '8'
  action:
    service: switch.turn_on
    entity_id: switch.laundry_room_overhead_switch

#-------------------------------------------
# Laundry Room No Motion
#-------------------------------------------
- alias: 'Laundry Room No Motion'
  hide_entity: true
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.laundry_multisensor_burglar
    from: '8'
    to: '0'
  action:
    service: switch.turn_off
    entity_id: switch.laundry_room_overhead_switch