#-------------------------------------------
# Listener Down
#-------------------------------------------
- alias: 'Listener Not Available Notice'
  initial_state: true
  trigger:
    - platform: time
      minutes: 5
      seconds: 00
  condition:
    condition: state
    entity_id: binary_sensor.listener
    state: 'off'
  action:
    - service: notify.telegram
      data:
        message: "\U0001F92C Unable to reach 345Mhz listener"