#-------------------------------------------
# Arrive Home
#-------------------------------------------
- alias: 'Chris Arrive Home'
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.chris_iphone_xs_ble
      from: 'off'
      to: 'on'
  condition:
    condition: state
    entity_id: device_tracker.chriss_iphone
    state: 'not_home'
  action:
    - service: notify.email
      data_template:
        message: "\U0001F513 Front Door Unlocked via Chris iPhone"
    - service: lock.unlock
      data:
        entity_id: lock.kwikset_touchpad_electronic_deadbolt_locked
