#-------------------------------------------
# Main Power Lost
#-------------------------------------------
- alias: 'Main Power Lost'
  initial_state: true
  hide_entity: true
  trigger:
    platform: state
    entity_id: sensor.synology_status_data
    from: 'OL'
  action:
    - service: notify.pushover_chris
      data:
        message: "\U0001F50B Main Power OFFLINE"
        title: "Main power lost, running on UPS power"
        data:
          sound: siren
          priority: 1

#-------------------------------------------
# Main Power Restored
#-------------------------------------------
- alias: 'Main Power Restored'
  initial_state: true
  hide_entity: true
  trigger:
    platform: state
    entity_id: sensor.synology_status_data
    to: 'OL'
  action:
    - service: notify.pushover_chris
      data:
        message: "\U0001F50C Main Power RESTORED"
        title: "Main power restored, now running on city power."
        data:
          priority: 0
