#-------------------------------------------
# Alert When UPS is running
#-------------------------------------------
- alias: 'Lost Power'
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.synology_status_data
    from: 'OL'
  action:
    - service: notify.primary_contact
      data_template:
        message: "\U0001F50B Main power lost, running on UPS power"