#-------------------------------------------
# Alert When UPS is running
#-------------------------------------------
- alias: 'Lost Power'
  trigger:
    platform: state
    entity_id: sensor.ups_status
    from: 'ONLINE'
    to: 'ONBATT'
  action:
    - service: notify.primary_contact
      data_template:
        message: "\U0001F50B Main power lost, running on UPS power"