#-------------------------------------------
# Main Power Lost Notice
#-------------------------------------------
- alias: 'Main Power Lost Notice'
  initial_state: true
  hide_entity: true
  trigger:
    platform: state
    entity_id: sensor.synology_status_data
    from: 'OL'
  action:
    - service: notify.sms
      data:
        message: "\U0001F50B Main power lost, running on UPS power"
        target:
          - !secret chris_mobile_num