#-------------------------------------------
# Wireless Tag Env Low Battery
#-------------------------------------------
- alias: 'Env Low Battery'
  initial_state: true
  hide_entity: true
  trigger:
    - platform: state
      entity_id: binary_sensor.clara_room_low_battery
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.clara_room_low_battery
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.guest_room_low_battery
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.kitchen_low_battery
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.masterbed_low_battery
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.play_area_low_battery
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.study_low_battery
      from: 'off'
      to: 'on'
  action:
    - service: notify.email
      data_template:
        message: "\U0001F50B Battery for the env sensor {{ trigger.to_state.attributes.friendly_name }} room is low.  It requires one CR2032 battery."

#-------------------------------------------
# PIR Low Battery
#-------------------------------------------
- alias: 'PIR Low Battery'
  initial_state: true
  hide_entity: true
  trigger:
    - platform: state
      entity_id: binary_sensor.laundry_room_low_battery
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.guest_bath_low_battery
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.master_bath_low_battery
      from: 'off'
      to: 'on'
  action:
    - service: notify.email
      data_template:
        message: "\U0001F50B Battery for the motion sensor in the {{ trigger.to_state.attributes.friendly_name }} room is low.  It requires one CR2450 battery."