#-------------------------------------------
# Wireless Tag Env Low Battery
#-------------------------------------------
- alias: 'Env Low Battery'
  initial_state: true
  hide_entity: true
  trigger:
    - platform: state
      entity_id: binary_sensor.clara_room_low_battery
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.clara_room_low_battery
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.guest_room_low_battery
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.kitchen_low_battery
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.masterbed_low_battery
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.play_area_low_battery
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.study_low_battery
      from: 'off'
      to: 'on'
  action:
    - service: notify.pushover_chris
      data_template:
        title: "\U0001F50B Env Sensor Low Battery"
        message: "The battery for the enviromental sensor {{ trigger.to_state.attributes.friendly_name }} room is low.  It requires one CR2032 battery."

#-------------------------------------------
# PIR Low Battery
#-------------------------------------------
- alias: 'PIR Low Battery'
  initial_state: true
  hide_entity: true
  trigger:
    - platform: state
      entity_id: binary_sensor.laundry_room_low_battery
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.guest_bath_low_battery
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.master_bath_low_battery
      from: 'off'
      to: 'on'
  action:
    - service: notify.pushover_chris
      data_template:
        title: "\U0001F50B PIR Low Battery"
        message: "The battery for the PIR / enviromental sensor in the {{ trigger.to_state.attributes.friendly_name }} room is low.  It requires one CR2450 battery."

#-------------------------------------------
# Door Lock Low Battery
#-------------------------------------------
- alias: 'Door Lock Low Battery'
  initial_state: true
  hide_entity: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.front_door_battery
      below: 60
    - platform: numeric_state
      entity_id: sensor.back_door_battery
      below: 60
    - platform: numeric_state
      entity_id: sensor.garage_door_battery
      below: 60
  action:
    - service: notify.pushover_chris
      data_template:
        title: "\U0001F50B Lock Low Battery"
        message: "The battery for {{ trigger.to_state.attributes.friendly_name }} is low.  It requires four AA batteries."
        data:
          sound: siren
          priority: 2