#-------------------------------------------
# Things to do when Megan gets home
#-------------------------------------------
- alias: 'Megan arrive home'
  initial_state: true
  trigger:
    platform: state
    entity_id: device_tracker.megan_iphone_8
    from: 'not_home'
    to: 'home'
  action:
    - service: lock.unlock
      data:
        entity_id: lock.front_door_locked