#-------------------------------------------
# Main Power Lost
#-------------------------------------------
- alias: 'Main Power Lost'
  initial_state: true
  hide_entity: true
  trigger:
    platform: state
    entity_id: sensor.synology_status_data
    from: 'OL'
  action:
    - service: notify.email
      data_template:
        title: "\U0001F50B Main Power Offline"
        message: "Main power lost, running on UPS power"