#-------------------------------------------
# Doorbell Action
#-------------------------------------------
- alias: 'Doorbell Action'
  initial_state: true
  hide_entity: true
  trigger:
    platform: state
    entity_id: binary_sensor.doorbell
    to: 'on'
  action:
    - service: camera.snapshot
      data_template:
        entity_id: camera.front_door
        filename: "/config/www/snapshots/front_door_camera_{{ trigger.to_state.last_changed }}.jpg"
    - service: notify.sms
      data_template:
        message: "\U0001F514 Someone is at the front door! https://ha.fuzzyblender.com/local/snapshots/front_door_camera_{{ trigger.to_state.last_changed|urlencode }}.jpg"
        target:
          - !secret chris_mobile
          - !secret megan_mobile
#    - service: media_player.volume_set
#      data:
#        entity_id: media_player.kitchen
#        volume_level: 0.20
#    - delay: '00:00:01'
    - service: media_player.play_media
      data:
        entity_id: media_player.kitchen
        media_content_id: https://has.fuzzyblender.com/local/doorbell.mp3
        media_content_type: 'music'