#-------------------------------------------
# Doorbell Action
#-------------------------------------------
- alias: 'Doorbell Action'
  initial_state: true
  hide_entity: true
  trigger:
    platform: state
    entity_id: sensor.doorbell
    to: 'ring'
  action:
    - service: camera.snapshot
      data_template:
        entity_id: camera.front_porch
        filename: "/config/www/snapshots/front_porch_camera_{{ trigger.to_state.last_changed }}.jpg"
    - service: notify.slack
      data_template:
        message: ''
        target: '#alerts'
        data:
          file:
            path: "/config/www/snapshots/front_porch_camera_{{ trigger.to_state.last_changed }}.jpg"
#          attachments:
#            - title: "\U0001F514 Someone is at the front door!"
#              color: warning
#              image_url: "https://plainrock.fuzzyblender.com:8123/local/snapshots/front_porch_camera_{{ image_file|urlencode }}.jpg"