#-------------------------------------------
# Doorbell Action
#-------------------------------------------
- alias: 'Doorbell Action'
  initial_state: true
  hide_entity: true
  trigger:
    platform: state
    entity_id: sensor.doorbell
    to: 'ring'
  action:
    - service: camera.snapshot
      data_template:
        entity_id: camera.front_porch
        filename: "/config/www/snapshots/front_porch_camera_{{ trigger.to_state.last_changed }}.jpg"
    - service: notify.sms
      data_template:
        message: "\U0001F514 Someone is at the front door! https://plainrock.fuzzyblender.com/local/snapshots/front_porch_camera_{{ trigger.to_state.last_changed|urlencode }}.jpg"
        target:
          - !secret chris_mobile
          - !secret megan_mobile