#-------------------------------------------
# Clara Room Low Battery
#-------------------------------------------
- alias: 'Clara Room Low Battery'
  initial_state: true
  hide_entity: true
  trigger:
    - platform: state
      entity_id: binary_sensor.clara_room_low_battery
      from: 'off'
      to: 'on'
  action:
    - service: notify.email
      data_template:
        title: "\U0001F50B Low Battery - Clara Room"
        message: "The battery for the enviromental sensor in Clara's room is low.  It requires one CR2032 battery."

#-------------------------------------------
# Guest Room Low Battery
#-------------------------------------------
- alias: 'Guest Room Low Battery'
  initial_state: true
  hide_entity: true
  trigger:
    - platform: state
      entity_id: binary_sensor.guest_room_low_battery
      from: 'off'
      to: 'on'
  action:
    - service: notify.email
      data_template:
        title: "\U0001F50B Low Battery - Guest Room"
        message: "The battery for the enviromental sensor in the guest room is low.  It requires one CR2032 battery."

#-------------------------------------------
# Kitchen Low Battery
#-------------------------------------------
- alias: 'Kitchen Low Battery'
  initial_state: true
  hide_entity: true
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_low_battery
      from: 'off'
      to: 'on'
  action:
    - service: notify.email
      data_template:
        title: "\U0001F50B Low Battery - Kitchen"
        message: "The battery for the enviromental sensor in the kitchen is low.  It requires one CR2032 battery."

#-------------------------------------------
# Laundry Room PIR Low Battery
#-------------------------------------------
- alias: 'Laundry Room Low Battery'
  initial_state: true
  hide_entity: true
  trigger:
    - platform: state
      entity_id: binary_sensor.laundry_room_low_battery
      from: 'off'
      to: 'on'
  action:
    - service: notify.email
      data_template:
        title: "\U0001F50B Low Battery - Laundry Room"
        message: "The battery for the PIR / enviromental sensor in the laundry room is low.  It requires one CR2450 battery."

#-------------------------------------------
# Master Bed Low Battery
#-------------------------------------------
- alias: 'Master Bed Low Battery'
  initial_state: true
  hide_entity: true
  trigger:
    - platform: state
      entity_id: binary_sensor.masterbed_low_battery
      from: 'off'
      to: 'on'
  action:
    - service: notify.email
      data_template:
        title: "\U0001F50B Low Battery - Master Bedroom"
        message: "The battery for the enviromental sensor in the master bedroom is low.  It requires one CR2032 battery."

#-------------------------------------------
# Play Area Low Battery
#-------------------------------------------
- alias: 'Play Area Low Battery'
  initial_state: true
  hide_entity: true
  trigger:
    - platform: state
      entity_id: binary_sensor.play_area_low_battery
      from: 'off'
      to: 'on'
  action:
    - service: notify.email
      data_template:
        title: "\U0001F50B Low Battery - Play Area"
        message: "The battery for the enviromental sensor in the play area is low.  It requires one CR2032 battery."

#-------------------------------------------
# Study Low Battery
#-------------------------------------------
- alias: 'Study Low Battery'
  initial_state: true
  hide_entity: true
  trigger:
    - platform: state
      entity_id: binary_sensor.study_low_battery
      from: 'off'
      to: 'on'
  action:
    - service: notify.email
      data_template:
        title: "\U0001F50B Low Battery - Study"
        message: "The battery for the enviromental sensor in the study is low.  It requires one CR2032 battery."

#-------------------------------------------
# Guest Bathroom PIR Low Battery
#-------------------------------------------
- alias: 'Guest Bathroom Low Battery'
  initial_state: true
  hide_entity: true
  trigger:
    - platform: state
      entity_id: binary_sensor.guest_bath_low_battery
      from: 'off'
      to: 'on'
  action:
    - service: notify.email
      data_template:
        title: "\U0001F50B Low Battery - Guest Bathroom"
        message: "The battery for the PIR / enviromental sensor in the guest bathroom is low.  It requires one CR2450 battery."

#-------------------------------------------
# Front Door Lock Low Battery
#-------------------------------------------
- alias: 'Front Door Lock Low Battery'
  initial_state: true
  hide_entity: true
  trigger:
    platform: numeric_state
    entity_id: sensor.front_door_battery
    below: 60
  action:
    - service: notify.email
      data_template:
        title: "\U0001F50B Low Battery - Front Door Lock"
        message: "The battery for the front door lock is low.  It requires four AA batteries."

#-------------------------------------------
# Back Door Lock Low Battery
#-------------------------------------------
- alias: 'Back Door Lock Low Battery'
  initial_state: true
  hide_entity: true
  trigger:
    platform: numeric_state
    entity_id: sensor.back_door_battery
    below: 60
  action:
    - service: notify.email
      data_template:
        title: "\U0001F50B Low Battery - Back Door Lock"
        message: "The battery for the back door lock is low.  It requires four AA batteries."

#-------------------------------------------
# Garage Door Lock Low Battery
#-------------------------------------------
- alias: 'Garage Door Lock Low Battery'
  initial_state: true
  hide_entity: true
  trigger:
    platform: numeric_state
    entity_id: sensor.garage_door_battery
    below: 60
  action:
    - service: notify.email
      data_template:
        title: "\U0001F50B Low Battery - Garage Door Lock"
        message: "The battery for the garage door lock is low.  It requires four AA batteries."