#-------------------------------------------
# No One Home
#-------------------------------------------
- alias: 'No One Home Actions'
  initial_state: true
  trigger:
    platform: state
    entity_id: group.family
    to: 'not_home'
    for:
      minutes: 10
  action:
    - service: script.away