#-------------------------------------------
# Overhead Garage Door Opened Notice
#-------------------------------------------
- alias: "Chris Garage Door Opened"
  initial_state: true
  hide_entity: true
  trigger:
    - platform: state
      entity_id: cover.chris_garage_door
      from: 'closed'
      to: 'open'
  condition:
    condition: state
    entity_id: input_boolean.enable_alerts
    state: 'on'
  action:
    - service: notify.pushover_chris
      data:
        title: "\U0001F697 Chris Garage Door Opened"
        message: "Hi! Chris Garage Door has been opened."
        data:
          priority: 1

#-------------------------------------------
# Overhead Garage Door Closed Notice
#-------------------------------------------
- alias: "Chris Garage Door Closed"
  initial_state: true
  hide_entity: true
  trigger:
    - platform: state
      entity_id: cover.chris_garage_door
      from: 'open'
      to: 'closed'
  condition:
    condition: state
    entity_id: input_boolean.enable_alerts
    state: 'on'
  action:
    - service: notify.pushover_chris
      data:
        title: "\U0001F697 Chris Garage Door Closed"
        message: "Hi! Chris Garage Door has been closed."
        data:
          priority: 1
