#-------------------------------------------
# Overhead Garage Door Opened Notice
#-------------------------------------------
- alias: "Overhead Garage Door Opened Notice"
  initial_state: true
  hide_entity: true
  trigger:
    - platform: state
      entity_id: binary_sensor.overhead_garage_one_sensor
      to: 'on'
      from: 'off'
    - platform: state
      entity_id: binary_sensor.overhead_garage_two_sensor
      to: 'on'
      from: 'off'
  action:
    - service: notify.telegram
      data:
        message: "\U0001F697 {{ trigger.to_state.attributes.friendly_name }} has been opened"