- alias: 'Weekend Mode'
  trigger:
    platform: time
    at: '08:00:00'
  condition:
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'off'
  action:
    - service: script.weekend_mode