- alias: 'Night Mode'
  trigger:
    platform: time
    at: '21:00:00'
  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
  action:
    - service: script.night_mode