#-------------------------------------------
#  Things for Sunrise
#-------------------------------------------
- alias: 'Sunrise'
  trigger:
    platform: sun
    event: sunrise
    offset: '+00:00:00'
  action:
    - service: light.turn_off
      data:
        entity_id: 
          - light.kitchen_sink_ove_level
    - service: switch.turn_off
      data:
        entity_id:
          - switch.backyard_switch
          - switch.frontyard_switch
    - service: climate.set_temperature
      data:
        entity_id: climate.hallway
        temperature: '72'
    - service: notify.primary_contact
      data:
        message: "Outside lights OFF, Temperature set to DAY level"