#-------------------------------------------
# Things to do at Sunrise
#-------------------------------------------
- alias: 'Sunrise'
  initial_state: true
  trigger:
    platform: sun
    event: sunrise
    offset: '+00:00:00'
  action:
    - service: script.sunrise