#-------------------------------------------
# Things to do at Sunset
#-------------------------------------------
- alias: 'Sunset'
  trigger:
    platform: sun
    event: sunset
  action:
    - service: script.sunset