#-------------------------------------------
# Sunset Actions
#-------------------------------------------
- alias: 'Sunset Actions'
  initial_state: true
  hide_entity: true
  trigger:
    platform: sun
    event: sunset
  action:
    - service: script.sunset