#-------------------------------------------
# Things to do at Sunset
#-------------------------------------------
- alias: 'Sunset'
  trigger:
    platform: sun
    event: sunset
    offset: '+01:00:00'
  action:
    - service: script.sunset