#-------------------------------------------
# Things to do at Sunset
#-------------------------------------------
- alias: 'Sunset'
  initial_state: true
  hide_entity: true
  trigger:
    platform: sun
    event: sunset
  action:
    - service: script.sunset