#-------------------------------------------
# Too Hot Alert
#-------------------------------------------
- alias: "Too Hot Alert"
  initial_state: true
  hide_entity: true
  trigger:
    platform: numeric_state
    entity_id: sensor.average_temperature
    above: 77
    for:
      minutes: 30
  action:
    - service: notify.pushover_chris
      data:
        title: "\U000026C4 High Temperature"
        message: "The average house temp is at or above 78 degrees"
        data:
          sound: siren
          priority: 2

#-------------------------------------------
# Too Cold Alert
#-------------------------------------------
- alias: "Too Cold Alert"
  initial_state: true
  hide_entity: true
  trigger:
    platform: numeric_state
    entity_id: sensor.average_temperature
    below: 64
    for:
      minutes: 30
  action:
    - service: notify.pushover_chris
      data:
        title: "\U000026C4 Low Temperature"
        message: "The average house temp is at or below 64 degrees"
        data:
          sound: siren
          priority: 2