#-------------------------------------------
# Too Hot Alert
#-------------------------------------------
- alias: "Too Hot Alert"
  initial_state: true
  hide_entity: true
  trigger:
    platform: numeric_state
    entity_id: sensor.average_temperature
    above: 80
    for:
      minutes: 30
  action:
    - service: notify.email
      data_template:
        message: "\U0001F4A7 Average house temp is at or above 80 degrees"

#-------------------------------------------
# Too Cold Alert
#-------------------------------------------
- alias: "Too Cold Alert"
  initial_state: true
  hide_entity: true
  trigger:
    platform: numeric_state
    entity_id: sensor.average_temperature
    below: 62
    for:
      minutes: 30
  action:
    - service: notify.email
      data_template:
        message: "\U0001F4A7  Average house temp is at or below 62 degree"
