#-------------------------------------------
# Winter / Autumn to 66 at night (HEAT)
#-------------------------------------------
- alias: 'Winter nights to 66'
  trigger:
    platform: time
    at: '18:00:00'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: sensor.season
        state: 'Winter'
      - condition: state
        entity_id: sensor.season
        state: 'Autumn'  
  action:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.hallway
        operation_mode: 'heat'
    - service: climate.set_temperature
      data:
        entity_id: climate.hallway
        temperature: 66

#-------------------------------------------
# Winter / Autumn to 68 durring day (HEAT)
#-------------------------------------------
- alias: 'Winter days to 68'
  trigger:
    platform: time
    at: '07:00:00'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: sensor.season
        state: 'Winter'
      - condition: state
        entity_id: sensor.season
        state: 'Autumn'  
  action:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.hallway
        operation_mode: 'heat'
    - service: climate.set_temperature
      data:
        entity_id: climate.hallway
        temperature: 68

#-------------------------------------------
# Summer to 72 durring day (COOL)
#-------------------------------------------
- alias: 'Summer days to 72'
  trigger:
    platform: time
    at: '07:00:00'
  condition:
    condition: state
      entity_id: sensor.season
      state: 'Summer'
  action:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.hallway
        operation_mode: 'cool'
    - service: climate.set_temperature
      data:
        entity_id: climate.hallway
        temperature: 72

#-------------------------------------------
# Summer to 72 durring night (COOL)
#-------------------------------------------
- alias: 'Summer nights to 68'
  trigger:
    platform: time
    at: '18:00:00'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: sensor.season
        state: 'Summer'
  action:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.hallway
        operation_mode: 'cool'
    - service: climate.set_temperature
      data:
        entity_id: climate.hallway
        temperature: 68