#-------------------------------------------
# Sunset Actions
#-------------------------------------------
- alias: 'Sunset Actions'
  initial_state: true
  hide_entity: true
  trigger:
    platform: sun
    event: sunset
  action:
    - service: switch.turn_on
      data:
        entity_id:
          - switch.front_yard_switch
          - switch.chris_bedside_switch
          - switch.megan_bedside_switch
          - switch.kitchen_island_switch
    - service: light.turn_on
      data:
        entity_id: 
          - light.kitchen_sink_level
        brightness: 40
    - service: lock.lock
      data:
        entity_id: group.all_locks
    - service: notify.email
      data_template:
        title: "\U0001F307 Have a good evening!"
        message: "The system has hit sunset mode.  Outside decorative lights are on, doors are locked, and inside lights were turned on."




        