#-------------------------------------------
# If House Gets too cold, warm to 68
#-------------------------------------------
- alias: 'Too cold'
  trigger:
    platform: numeric_state
    entity_id: climate.hallway
    value_template: '{{states.climate.hallway.attributes.current_temperature}}'
    below: 67
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: sensor.season
        state: 'Winter'
      - condition: state
        entity_id: sensor.season
        state: 'Autumn'  
  action:
    - service: script.warm_to_68