#-------------------------------------------
# Unlock the door when arrive home (use tile?)
#-------------------------------------------
- alias: 'Unlock the door when arrive home'
  initial_state: true
  trigger:
    - platform: state
      entity_id: device_tracker.chris_iphone_x
      from: 'not_home'
      to: 'home'
    - platform: state
      entity_id: device_tracker.megan_iphone_8
      from: 'not_home'
      to: 'home'
  condition:
    condition: time
    after: '08:00:00'
    before: '16:00:00'
  action:
    - service: lock.unlock
      data:
        entity_id: lock.front_door_locked