- alias: 'Update Available Notifications'
  initial_state: true
  hide_entity: true
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    - service: persistent_notification.create
      data:
        title: 'Software Update'
        message: 'Update for Home Assistant is available'
    - service: notify.email_admins
      data:
        title: 'New Home Assistant is avaiable'
        message: 'There is an update for Home Assistant.  Check it out at https://home-assistant.io'
