- alias: 'Update Available Notifications'
  initial_state: true
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    - service: persistent_notification.create
      data:
        message: 'Update for Home Assistant is available'
        title: 'Software Update'
    - service: notify.sms
      data:
        message: 'Update for Home Assistant is available'
        target:
          - !secret chris_mobile_num