#-------------------------------------------
# Windows Opened, send alert, turn off HVAC
#-------------------------------------------
- alias: "Window Opened"
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.all_windows
      from: 'closed'
      to: 'open'
  action:
    - service: notify.primary_contact
      data_template:
        message: "\U0001F6A8 {{ trigger.to_state.attributes.friendly_name }} has been OPENED, HVAC has been turned off"
    - service: climate.set_operation_mode
      entity_id: climate.hallway
      data:
        operation_mode: "off"

#-------------------------------------------
# Windows Closed, send alert, turn on HVAC
#-------------------------------------------
- alias: "Window Opened"
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.all_windows
      from: 'open'
      to: 'closed'
  action:
    - service: notify.primary_contact
      data_template:
        message: "\U0001F6A8 {{ trigger.to_state.attributes.friendly_name }} has been CLOSED, resuming HVAC operations"
    - service: climate.set_operation_mode
      entity_id: climate.hallway
      data:
        operation_mode: "auto"