#-------------------------------------------
# Window(s) Opened
#-------------------------------------------
- alias: "Window Opened"
  initial_state: true
  hide_entity: true
  trigger:
    platform: state
    entity_id: sensor.all_windows
    from: 'closed'
    to: 'open'
  action:
    - service: notify.telegram
      data:
        message: "\U0001F6A8 A window has been opened, HVAC has been turned off"
    - service: climate.set_operation_mode
      entity_id: climate.hallway
      data:
        operation_mode: "off"