- alias: "Window Opened"
  trigger:
    - platform: state
      entity_id: binary_sensor.study_window
      to: 'on'
      from: 'off'
    - platform: state
      entity_id: binary_sensor.master_bathroom_window
      to: 'on'
      from: 'off'
    - platform: state
      entity_id: binary_sensor.guest_window
      to: 'on'
      from: 'off'
    - platform: state
      entity_id: binary_sensor.child_window
      to: 'on'
      from: 'off'
    - platform: state
      entity_id: binary_sensor.front_right_window
      to: 'on'
      from: 'off'
    - platform: state
      entity_id: binary_sensor.front_window_one
      to: 'on'
      from: 'off'
    - platform: state
      entity_id: binary_sensor.front_window_two
      to: 'on'
      from: 'off'
    - platform: state
      entity_id: binary_sensor.back_window_one
      to: 'on'
      from: 'off'
    - platform: state
      entity_id: binary_sensor.back_window_two
      to: 'on'
      from: 'off'
    - platform: state
      entity_id: binary_sensor.back_window_three
      to: 'on'
      from: 'off'
    - platform: state
      entity_id: binary_sensor.back_right_window
      to: 'on'
      from: 'off'
    - platform: state
      entity_id: binary_sensor.kitchen_sink_window
      to: 'on'
      from: 'off'
    - platform: state
      entity_id: binary_sensor.master_bedroom_window
      to: 'on'
      from: 'off'
    - platform: state
      entity_id: binary_sensor.back_right_window
      to: 'on'
      from: 'off'
  action:
    - service: script.window_opened