#-------------------------------------------
# Window(s) Opened Actions
#-------------------------------------------
- alias: "Window Opened Actions"
  initial_state: true
  hide_entity: true
  trigger:
    platform: state
    entity_id: sensor.all_windows
    from: 'closed'
    to: 'open'
  action:
    - service: notify.sms
      data_template:
        message: "\U0001F6A8 {{ trigger.to_state.attributes.friendly_name }} has been opened, HVAC has been turned off"
        target:
          - !secret chris_mobile_num
          - !secret megan_mobile_num 
    - service: climate.set_operation_mode
      entity_id: climate.hallway
      data:
        operation_mode: "off"