#-------------------------------------------
# Window(s) opened turn off HVAC
#-------------------------------------------
- alias: "Window Opened HVAC Off"
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.all_windows
      from: 'closed'
      to: 'open'
  action:
    - service: notify.sms
      data:
        message: "\U0001F6A8 {{ trigger.to_state.attributes.friendly_name }} has been opened, HVAC has been turned off"
        target:
          - !secret chris_mobile_num
          - !secret megan_mobile_num 
    - service: climate.set_operation_mode
      entity_id: climate.hallway
      data:
        operation_mode: "off"

#-------------------------------------------
# Window(s) closed turn on HVAC
#-------------------------------------------
- alias: "Window Closed HVAC On"
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.all_windows
      from: 'open'
      to: 'closed'
  action:
    - service: notify.sms
      data:
        message: "\U0001F6A8 {{ trigger.to_state.attributes.friendly_name }} has been closed, resuming HVAC operations"
        target:
          - !secret chris_mobile_num
          - !secret megan_mobile_num 
    - service: climate.set_operation_mode
      entity_id: climate.hallway
      data:
        operation_mode: "auto"