- alias: "Window Opened"
  trigger:
    - platform: state
      entity_id: binary_sensor.study_window
      to: 'on'
      from: 'off'
    - platform: state
      entity_id: binary_sensor.master_bathroom_window
      to: 'on'
      from: 'off'
    - platform: state
      entity_id: binary_sensor.guest_window
      to: 'on'
      from: 'off'
    - platform: state
      entity_id: binary_sensor.child_window
      to: 'on'
      from: 'off'
    - platform: state
      entity_id: binary_sensor.front_right_window
      to: 'on'
      from: 'off'
    - platform: state
      entity_id: binary_sensor.front_window_one
      to: 'on'
      from: 'off'
    - platform: state
      entity_id: binary_sensor.front_window_two
      to: 'on'
      from: 'off'
    - platform: state
      entity_id: binary_sensor.back_window_one
      to: 'on'
      from: 'off'
    - platform: state
      entity_id: binary_sensor.back_window_two
      to: 'on'
      from: 'off'
    - platform: state
      entity_id: binary_sensor.back_window_three
      to: 'on'
      from: 'off'
    - platform: state
      entity_id: binary_sensor.back_right_window
      to: 'on'
      from: 'off'
    - platform: state
      entity_id: binary_sensor.kitchen_sink_window
      to: 'on'
      from: 'off'
    - platform: state
      entity_id: binary_sensor.master_bedroom_window
      to: 'on'
      from: 'off'
    - platform: state
      entity_id: binary_sensor.back_right_window
      to: 'on'
      from: 'off'
  action:
    - service: notify.primary_contact
      data_template:
        message: "\U0001F6A8 {{ trigger.to_state.attributes.friendly_name }} has been OPENED"
    - service: climate.set_operation_mode
      entity_id: climate.hallway
      data:
        operation_mode: "off"