#-------------------------------------------
# Doorbell Action
#-------------------------------------------
- alias: 'Doorbell Action'
  initial_state: true
  hide_entity: true
  trigger:
    platform: state
    entity_id: sensor.doorbell
#    from: 'off'
    to: 'ring'
  action:
    - service: camera.snapshot
      data_template:
        entity_id: camera.front_porch
        filename: /config/www/front_door_camera_{{ trigger.to_state.last_changed }}.jpg
    - service: notify.sms
      data_template:
        message: 'Someone is at the door.  https://plainrock.fuzzyblender.com:8123/local/front_door_camera_{{ trigger.to_state.last_changed|urlencode }}.jpg'
        target:
          - !secret chris_mobile_num
#          - !secret megan_mobile_num