#-------------------------------------------
# Laundry Room Motion Actions
#-------------------------------------------
- alias: 'Laundry Room Motion Actions'
  hide_entity: true
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.laundry_multisensor_burglar
    from: '0'
    to: '8'
  action:
    service: switch.turn_on
    entity_id: switch.laundry_room_overhead_switch

#-------------------------------------------
# Laundry Room No Motion Actions
#-------------------------------------------
- alias: 'Laundry Room No Motion Actions'
  hide_entity: true
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.laundry_multisensor_burglar
    from: '8'
    to: '0'
  action:
    service: switch.turn_off
    entity_id: switch.laundry_room_overhead_switch