#-------------------------------------------
# Sunrise Actions
#-------------------------------------------
- alias: 'Sunrise Actions'
  initial_state: true
  hide_entity: true
  trigger:
    platform: sun
    event: sunrise
    offset: '+00:00:00'
  action:
    - service: script.sunrise