#-------------------------------------------
#  Settings Tab
#-------------------------------------------
settings:
  name: Settings
  view: yes
  icon: mdi:settings
  entities:
    - group.all_automations
    - group.house_mode
    - group.rf_heartbeats