#-------------------------------------------
#  System Tab
#-------------------------------------------
system_tab:
  name: System
  view: yes
  icon: mdi:settings
  entities:
    - group.all_automations
    - group.house_mode
    - group.rf_heartbeats
    - group.devices
    - group.system
    - group.apcupsd
    - group.links