#-------------------------------------------
#  System Tab
#-------------------------------------------
system_tab:
  name: System
  view: yes
  icon: mdi:settings
  entities:
    - group.system
    - group.apcupsd
    - group.battery_levels
    - group.connection