#-------------------------------------------
#  Away Mode
#-------------------------------------------
automation:
  - alias: "Away Mode"
    trigger:
      platform: state
      entity_id: group.family
      to: 'not_home'
      for:
        minutes: 10
    condition:
      - condition: state
        entity_id: group.family
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
    action:
      - service: light.turn_off
      - service: switch.turn_off
      - service: lock.lock
        entity_id: group.all_locks
      - service: notify.primary_contact
        data:
          message: "Away Mode.  Lights OFF, Doors LOCKED"