#-------------------------------------------
# Send an alert when a door is unlocked
#-------------------------------------------
automation:
  - alias: "Door Unlocked"
    - platform: template
#      value_template: >
#        {% for lock in states.lock if lock.attributes.locked %}
#          {%- if lock.attributes.locked | int < 70 -%}
#            {{true}}
#          {%- endif -%}
#        {%- endfor -%}
    trigger:
      - platform: state
        entity_id: lock.back_door_locked
        to: 'unlocked'
        from: 'locked'
      - platform: state
        entity_id: lock.garage_door_locked
        to: 'unlocked'
        from: 'locked'
      - platform: state
        entity_id: lock.front_door_locked
        to: 'unlocked'
        from: 'locked'
    action:
      service: notify.primary_contact
      data_template:
        message: "{{ trigger.to_state.attributes.friendly_name }} has been UNLOCKED"

#-------------------------------------------
  - alias: "Night Auto-Lock"
    trigger:
      platform: time
      at: '21:00:00'
    action:
      - service: lock.lock
        entity_id: group.all_locks
      - service: notify.primary_contact
        data:
          message: "All doors have been LOCKED" 