#-------------------------------------------
# APCUPSd Package Things
#-------------------------------------------
apcupsd:
  host: !secret apcupsd_host

#-------------------------------------------
group:
  ups:
    name: UPS
    entities:
      - sensor.ups_battery
      - sensor.ups_input_voltage
      - sensor.ups_load
      - sensor.ups_status
      - sensor.ups_time_left
      - sensor.ups_time_on_battery

#-------------------------------------------
binary_sensor:
  - platform: apcupsd

#-------------------------------------------
sensor:
  - platform: apcupsd
    resources:
      - bcharge
      - linev
      - loadpct
      - nominv
      - nompower
      - numxfers
      - status
      - timeleft
      - tonbatt