#-------------------------------------------
# Weather Package
#-------------------------------------------
sensor:
  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
      - summary
      - icon
      - nearest_storm_distance
      - precip_probability
      - humidity
      - temperature

#-------------------------------------------
  - platform: wunderground
    api_key: !secret wunderground_api_key
    monitored_conditions:
      - alerts

#-------------------------------------------
group:
  weather:
    name: Weather
    entities:
      - sensor.dark_sky_summary
      - sensor.dark_sky_nearest_storm_distance
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_humidity
      - sensor.dark_sky_temperature

#-------------------------------------------
binary_sensor:
  - platform: template
    sensors:
      severe_weather:
        value_template: >
          {%- if is_state("sensor.pws_alerts", "0") -%}
          False
          {%- else -%}
          True
          {%- endif -%}

#-------------------------------------------
alert:
  severe_weather:
    name: There is a severe weather alert
    done_message: No active severe weather alerts
    entity_id: binary_sensor.severe_weather
    repeat: 15
    notifiers:
      - primary_contact