#-------------------------------------------
#  Garage Motion Sensor
#-------------------------------------------
- platform: template
  sensors:
    garage_multisensor_motion:
      friendly_name: 'Garage MultiSensor Motion'
      value_template: >-
        {% if is_state('sensor.aeotec_zw100_multisensor_6_burglar', '8') %}
          motion
        {% elif is_state('sensor.aeotec_zw100_multisensor_6_burglar', '3') %}
          tamper
        {% else %}
          still
        {% endif %}

#-------------------------------------------
#  Garage Battery Sensor
#-------------------------------------------
- platform: template
  sensors:
    garage_multisensor_battery:
      friendly_name: 'Garage Multisensor'
      value_template: >-
        {% if states.zwave._ %}
          {{ states.zwave._.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'
      icon_template: >-
        {% set battery_level = states('sensor.garage_multisensor_battery')|int('unknown') %}
        {% set battery_round = (battery_level|int / 10)|int * 10 %}
        {% if battery_level == 'unknown' %}
          mdi:battery-unknown
        {% else %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
        {% endif %}