#-------------------------------------------
#  Guest Bath Motion Sensor
#-------------------------------------------
- platform: template
  sensors:
    guest_bath_multisensor_motion:
      friendly_name: 'Guest Bath MultiSensor Motion'
      value_template: >-
        {% if is_state('sensor.guest_bath_multisensor_burglar', '8') %}
          motion
        {% elif is_state('sensor.guest_bath_multisensor_burglar', '3') %}
          tamper
        {% else %}
          still
        {% endif %}