#-------------------------------------------
#  Guest Room Motion Sensor
#-------------------------------------------
- platform: template
  sensors:
    guest_multisensor_motion:
      friendly_name: 'Guest MultiSensor Motion'
      value_template: >-
        {% if is_state('sensor.guest_multisensor_burglar', '8') %}
          motion
        {% elif is_state('sensor.guest_multisensor_burglar', '3') %}
          tamper
        {% else %}
          still
        {% endif %}