#-------------------------------------------
#  Kitchen Motion Sensor
#-------------------------------------------
- platform: template
  sensors:
    kitchen_multisensor_motion:
      friendly_name: 'Kitchen MultiSensor Motion'
      value_template: >-
        {% if is_state('sensor.kitchen_multisensor_burglar', '8') %}
          motion
        {% elif is_state('sensor.kitchen_multisensor_burglar', '3') %}
          tamper
        {% else %}
          still
        {% endif %}