#-------------------------------------------
#  Kitchen Motion Sensor
#-------------------------------------------
- platform: template
  sensors:
    kitchen_multisensor_motion:
      friendly_name: 'Kitchen MultiSensor Motion'
      value_template: >-
        {% if is_state('sensor.kitchen_multisensor_burglar', '8') %}
          motion
        {% elif is_state('sensor.kitchen_multisensor_burglar', '3') %}
          tamper
        {% else %}
          still
        {% endif %}

#-------------------------------------------
#  Kitchen Multisensor
#-------------------------------------------
- platform: template
  sensors:
    kitchen_multisensor_battery:
      friendly_name: 'Kitchen Multisensor'
      value_template: '{% if states.zwave.kitchen_multisensor.attributes.battery_level %}
        {{ states.zwave.kitchen_multisensor.attributes.battery_level }}
      {% else %}
        unknown
      {% endif %}'      
      unit_of_measurement: '%'
      entity_id: zwave.kitchen_multisensor
      icon_template: >-
        {% set battery_level = states('sensor.kitchen_multisensor_battery')|int('unknown') %}
        {% set battery_round = (battery_level|int / 10)|int * 10 %}
        {% if battery_level == 'unknown' %}
          mdi:battery-unknown
        {% else %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
        {% endif %}