#-------------------------------------------
#  Master Bath Motion Sensor
#-------------------------------------------
- platform: template
  sensors:
    master_bath_multisensor_motion:
      friendly_name: 'Master Bath MultiSensor Motion'
      value_template: >-
        {% if is_state('sensor.master_bath_multisensor_burglar', '8') %}
          motion
        {% elif is_state('sensor.master_bath_multisensor_burglar', '3') %}
          tamper
        {% else %}
          still
        {% endif %}

#-------------------------------------------
#  Master Bath Multisensor
#-------------------------------------------
- platform: template
  sensors:
    master_bath_multisensor_battery:
      friendly_name: 'Master Bath Multisensor'
      value_template: >-
        {% if states.zwave.master_bath_multisensor %}
          {{ states.zwave.master_bath_multisensor.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %}  
      unit_of_measurement: '%'
      entity_id: zwave.master_bath_multisensor
      icon_template: >-
        {% set battery_level = states('sensor.master_bath_multisensor_battery')|int('unknown') %}
        {% set battery_round = (battery_level|int / 10)|int * 10 %}
        {% if battery_level == 'unknown' %}
          mdi:battery-unknown
        {% else %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
        {% endif %}