#-------------------------------------------
#  Study Motion Sensor
#-------------------------------------------
- platform: template
  sensors:
    study_multisensor_motion:
      friendly_name: 'Study MultiSensor Motion'
      value_template: >-
        {% if is_state('sensor.study_multisensor_burglar', '8') %}
          motion
        {% elif is_state('sensor.study_multisensor_burglar', '3') %}
          tamper
        {% else %}
          still
        {% endif %}