#-------------------------------------------
#  TV Room Motion Sensor
#-------------------------------------------
- platform: template
  sensors:
    tv_room_multisensor_motion:
      friendly_name: 'TV Room MultiSensor Motion'
      value_template: >-
        {% if is_state('sensor.tv_room_multisensor_burglar', '8') %}
          motion
        {% elif is_state('sensor.tv_room_multisensor_burglar', '3') %}
          tamper
        {% else %}
          still
        {% endif %}

#-------------------------------------------
#  TV Room Multisensor
#-------------------------------------------
- platform: template
  sensors:
    tv_room_multisensor_battery: 
      friendly_name: 'TV Room Multisensor'
      value_template: >-
        {% if states.zwave.tv_room_multisensor %}
          {{ states.zwave.tv_room_multisensor.attributes.battery_level }}
        {% else %}
          unknown
        {% endif %} 
      unit_of_measurement: '%'
      icon_template: >-
        {% set battery_level = states('sensor.tv_room_multisensor_battery')|int('unknown') %}
        {% set battery_round = (battery_level|int / 10)|int * 10 %}
        {% if battery_level == 'unknown' %}
          mdi:battery-unknown
        {% else %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
        {% endif %}